// Package subsonic provides scoped library access helpers that wrap the sqlc-generated
// queries. "Scoped" means the query enforces that the caller can only see songs (and
// the artists/albums derived from them) that belong to the user or are inside a folder
// node shared to the user via resource_shares.
//
// All public queries live in internal/db/music.sql.go (generated by sqlc). This file
// is a thin home for any Go-level helpers that sit on top of those queries; currently
// it is intentionally sparse — browse.go calls h.q.Accessible* directly.
package subsonic
