// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpBookmarkGCSeq = `-- name: BumpBookmarkGCSeq :exec
UPDATE users SET bookmark_gc_seq = GREATEST(bookmark_gc_seq, $2) WHERE id = $1
`

type BumpBookmarkGCSeqParams struct {
	ID            pgtype.UUID `json:"id"`
	BookmarkGcSeq int64       `json:"bookmark_gc_seq"`
}

func (q *Queries) BumpBookmarkGCSeq(ctx context.Context, arg BumpBookmarkGCSeqParams) error {
	_, err := q.db.Exec(ctx, bumpBookmarkGCSeq, arg.ID, arg.BookmarkGcSeq)
	return err
}

const createBrowserBookmark = `-- name: CreateBrowserBookmark :one
WITH s AS (
    UPDATE users SET bookmark_seq = bookmark_seq + 1 WHERE id = $1 RETURNING bookmark_seq
)
INSERT INTO browser_bookmarks (id, user_id, parent_id, is_folder, title, url, position, seq)
VALUES (COALESCE($6::uuid, gen_random_uuid()), $1, $7, $2, $3, $4, $5,
        (SELECT bookmark_seq FROM s))
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at
`

type CreateBrowserBookmarkParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	IsFolder bool        `json:"is_folder"`
	Title    string      `json:"title"`
	Url      string      `json:"url"`
	Position int32       `json:"position"`
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateBrowserBookmark(ctx context.Context, arg CreateBrowserBookmarkParams) (BrowserBookmark, error) {
	row := q.db.QueryRow(ctx, createBrowserBookmark,
		arg.UserID,
		arg.IsFolder,
		arg.Title,
		arg.Url,
		arg.Position,
		arg.ID,
		arg.ParentID,
	)
	var i BrowserBookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.IsFolder,
		&i.Title,
		&i.Url,
		&i.Position,
		&i.Deleted,
		&i.Seq,
		&i.FaviconExt,
		&i.FaviconTriedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gCBrowserBookmarkTombstones = `-- name: GCBrowserBookmarkTombstones :many
DELETE FROM browser_bookmarks
WHERE deleted AND updated_at < $1
RETURNING id, user_id, favicon_ext, seq
`

type GCBrowserBookmarkTombstonesRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	FaviconExt string      `json:"favicon_ext"`
	Seq        int64       `json:"seq"`
}

func (q *Queries) GCBrowserBookmarkTombstones(ctx context.Context, updatedAt pgtype.Timestamptz) ([]GCBrowserBookmarkTombstonesRow, error) {
	rows, err := q.db.Query(ctx, gCBrowserBookmarkTombstones, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GCBrowserBookmarkTombstonesRow{}
	for rows.Next() {
		var i GCBrowserBookmarkTombstonesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FaviconExt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarkSyncState = `-- name: GetBookmarkSyncState :one
SELECT bookmark_seq, bookmark_gc_seq FROM users WHERE id = $1
`

type GetBookmarkSyncStateRow struct {
	BookmarkSeq   int64 `json:"bookmark_seq"`
	BookmarkGcSeq int64 `json:"bookmark_gc_seq"`
}

func (q *Queries) GetBookmarkSyncState(ctx context.Context, id pgtype.UUID) (GetBookmarkSyncStateRow, error) {
	row := q.db.QueryRow(ctx, getBookmarkSyncState, id)
	var i GetBookmarkSyncStateRow
	err := row.Scan(&i.BookmarkSeq, &i.BookmarkGcSeq)
	return i, err
}

const getBrowserBookmarkForUser = `-- name: GetBrowserBookmarkForUser :one
SELECT id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at FROM browser_bookmarks WHERE id = $1 AND user_id = $2
`

type GetBrowserBookmarkForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetBrowserBookmarkForUser(ctx context.Context, arg GetBrowserBookmarkForUserParams) (BrowserBookmark, error) {
	row := q.db.QueryRow(ctx, getBrowserBookmarkForUser, arg.ID, arg.UserID)
	var i BrowserBookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.IsFolder,
		&i.Title,
		&i.Url,
		&i.Position,
		&i.Deleted,
		&i.Seq,
		&i.FaviconExt,
		&i.FaviconTriedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrowserBookmarkChanges = `-- name: ListBrowserBookmarkChanges :many
SELECT id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at FROM browser_bookmarks
WHERE user_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListBrowserBookmarkChangesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Seq    int64       `json:"seq"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListBrowserBookmarkChanges(ctx context.Context, arg ListBrowserBookmarkChangesParams) ([]BrowserBookmark, error) {
	rows, err := q.db.Query(ctx, listBrowserBookmarkChanges, arg.UserID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrowserBookmark{}
	for rows.Next() {
		var i BrowserBookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.IsFolder,
			&i.Title,
			&i.Url,
			&i.Position,
			&i.Deleted,
			&i.Seq,
			&i.FaviconExt,
			&i.FaviconTriedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrowserBookmarks = `-- name: ListBrowserBookmarks :many

SELECT id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at FROM browser_bookmarks
WHERE user_id = $1 AND NOT deleted
ORDER BY parent_id NULLS FIRST, position, title
`

// Bookmarks: server-authoritative tree with per-user seq cursor + tombstones.
// Every mutation bumps users.bookmark_seq via a CTE in the same statement: the
// row lock on users serializes a user's mutations, so per-user commit order
// equals seq order and a committed bookmark_seq is always a safe cursor.
func (q *Queries) ListBrowserBookmarks(ctx context.Context, userID pgtype.UUID) ([]BrowserBookmark, error) {
	rows, err := q.db.Query(ctx, listBrowserBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrowserBookmark{}
	for rows.Next() {
		var i BrowserBookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.IsFolder,
			&i.Title,
			&i.Url,
			&i.Position,
			&i.Deleted,
			&i.Seq,
			&i.FaviconExt,
			&i.FaviconTriedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrowserBookmarksNeedingFavicon = `-- name: ListBrowserBookmarksNeedingFavicon :many
SELECT id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at FROM browser_bookmarks
WHERE favicon_tried_at IS NULL AND NOT deleted AND NOT is_folder
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListBrowserBookmarksNeedingFavicon(ctx context.Context, limit int32) ([]BrowserBookmark, error) {
	rows, err := q.db.Query(ctx, listBrowserBookmarksNeedingFavicon, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrowserBookmark{}
	for rows.Next() {
		var i BrowserBookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.IsFolder,
			&i.Title,
			&i.Url,
			&i.Position,
			&i.Deleted,
			&i.Seq,
			&i.FaviconExt,
			&i.FaviconTriedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveBrowserBookmark = `-- name: MoveBrowserBookmark :one
WITH RECURSIVE s AS (
    UPDATE users SET bookmark_seq = bookmark_seq + 1 WHERE id = $1 RETURNING bookmark_seq
), sub AS (
    SELECT b.id FROM browser_bookmarks b WHERE b.id = $2 AND b.user_id = $1
    UNION ALL
    SELECT c.id FROM browser_bookmarks c JOIN sub ON c.parent_id = sub.id WHERE c.user_id = $1
)
UPDATE browser_bookmarks SET
    parent_id = $3,
    seq = (SELECT bookmark_seq FROM s),
    updated_at = now()
WHERE browser_bookmarks.id = $2 AND browser_bookmarks.user_id = $1 AND NOT deleted
  AND NOT EXISTS (SELECT 1 FROM sub WHERE sub.id = $3)
RETURNING id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at
`

type MoveBrowserBookmarkParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

// MoveBookmark re-parents a node. The NOT EXISTS guard rejects a move that
// would create a cycle (the target parent must not be inside the moved subtree).
func (q *Queries) MoveBrowserBookmark(ctx context.Context, arg MoveBrowserBookmarkParams) (BrowserBookmark, error) {
	row := q.db.QueryRow(ctx, moveBrowserBookmark, arg.UserID, arg.ID, arg.ParentID)
	var i BrowserBookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.IsFolder,
		&i.Title,
		&i.Url,
		&i.Position,
		&i.Deleted,
		&i.Seq,
		&i.FaviconExt,
		&i.FaviconTriedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextBookmarkSeq = `-- name: NextBookmarkSeq :one
UPDATE users SET bookmark_seq = bookmark_seq + 1 WHERE id = $1 RETURNING bookmark_seq
`

func (q *Queries) NextBookmarkSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextBookmarkSeq, id)
	var bookmark_seq int64
	err := row.Scan(&bookmark_seq)
	return bookmark_seq, err
}

const setBrowserBookmarkFavicon = `-- name: SetBrowserBookmarkFavicon :exec
UPDATE browser_bookmarks SET favicon_ext = $2, favicon_tried_at = now() WHERE id = $1
`

type SetBrowserBookmarkFaviconParams struct {
	ID         pgtype.UUID `json:"id"`
	FaviconExt string      `json:"favicon_ext"`
}

// SetBookmarkFavicon does NOT bump seq: favicons are server-side decoration,
// browsers don't need to re-pull the node.
func (q *Queries) SetBrowserBookmarkFavicon(ctx context.Context, arg SetBrowserBookmarkFaviconParams) error {
	_, err := q.db.Exec(ctx, setBrowserBookmarkFavicon, arg.ID, arg.FaviconExt)
	return err
}

const setBrowserBookmarkTitleIfEmpty = `-- name: SetBrowserBookmarkTitleIfEmpty :execrows
WITH s AS (
    UPDATE users SET bookmark_seq = bookmark_seq + 1 WHERE id = $1 RETURNING bookmark_seq
)
UPDATE browser_bookmarks SET title = $3, seq = (SELECT bookmark_seq FROM s), updated_at = now()
WHERE browser_bookmarks.id = $2 AND browser_bookmarks.user_id = $1
  AND browser_bookmarks.title = '' AND NOT deleted
`

type SetBrowserBookmarkTitleIfEmptyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
	Title  string      `json:"title"`
}

func (q *Queries) SetBrowserBookmarkTitleIfEmpty(ctx context.Context, arg SetBrowserBookmarkTitleIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBrowserBookmarkTitleIfEmpty, arg.UserID, arg.ID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tombstoneBrowserBookmarkTree = `-- name: TombstoneBrowserBookmarkTree :execrows
WITH RECURSIVE sub AS (
    SELECT b.id FROM browser_bookmarks b WHERE b.id = $2 AND b.user_id = $1
    UNION ALL
    SELECT c.id FROM browser_bookmarks c JOIN sub ON c.parent_id = sub.id WHERE c.user_id = $1
)
UPDATE browser_bookmarks SET deleted = true, seq = $3, updated_at = now()
WHERE id IN (SELECT id FROM sub) AND NOT deleted
`

type TombstoneBrowserBookmarkTreeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
	Seq    int64       `json:"seq"`
}

// TombstoneBookmarkTree marks the whole subtree deleted with one seq value
// (valid: the cursor needs per-row monotonicity, not uniqueness). Runs inside
// a tx after NextBookmarkSeq.
func (q *Queries) TombstoneBrowserBookmarkTree(ctx context.Context, arg TombstoneBrowserBookmarkTreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneBrowserBookmarkTree, arg.UserID, arg.ID, arg.Seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBrowserBookmark = `-- name: UpdateBrowserBookmark :one
WITH s AS (
    UPDATE users SET bookmark_seq = bookmark_seq + 1 WHERE id = $1 RETURNING bookmark_seq
)
UPDATE browser_bookmarks SET
    title = COALESCE($3, title),
    url = COALESCE($4, url),
    position = COALESCE($5, position),
    seq = (SELECT bookmark_seq FROM s),
    updated_at = now()
WHERE browser_bookmarks.id = $2 AND browser_bookmarks.user_id = $1 AND NOT deleted
RETURNING id, user_id, parent_id, is_folder, title, url, position, deleted, seq, favicon_ext, favicon_tried_at, created_at, updated_at
`

type UpdateBrowserBookmarkParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ID       pgtype.UUID `json:"id"`
	Title    pgtype.Text `json:"title"`
	Url      pgtype.Text `json:"url"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateBrowserBookmark(ctx context.Context, arg UpdateBrowserBookmarkParams) (BrowserBookmark, error) {
	row := q.db.QueryRow(ctx, updateBrowserBookmark,
		arg.UserID,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Position,
	)
	var i BrowserBookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.IsFolder,
		&i.Title,
		&i.Url,
		&i.Position,
		&i.Deleted,
		&i.Seq,
		&i.FaviconExt,
		&i.FaviconTriedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBrowserBookmarkAt = `-- name: UpsertBrowserBookmarkAt :exec
INSERT INTO browser_bookmarks (id, user_id, parent_id, is_folder, title, url, position, seq)
VALUES ($1, $2, $8, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    is_folder = EXCLUDED.is_folder,
    title = EXCLUDED.title,
    url = EXCLUDED.url,
    position = EXCLUDED.position,
    deleted = false,
    seq = EXCLUDED.seq,
    updated_at = now()
WHERE browser_bookmarks.user_id = EXCLUDED.user_id
`

type UpsertBrowserBookmarkAtParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	IsFolder bool        `json:"is_folder"`
	Title    string      `json:"title"`
	Url      string      `json:"url"`
	Position int32       `json:"position"`
	Seq      int64       `json:"seq"`
	ParentID pgtype.UUID `json:"parent_id"`
}

// UpsertBookmarkAt is the bulk-import step (tx, seq passed in). LWW: an
// existing row (including a tombstone) is overwritten and revived.
func (q *Queries) UpsertBrowserBookmarkAt(ctx context.Context, arg UpsertBrowserBookmarkAtParams) error {
	_, err := q.db.Exec(ctx, upsertBrowserBookmarkAt,
		arg.ID,
		arg.UserID,
		arg.IsFolder,
		arg.Title,
		arg.Url,
		arg.Position,
		arg.Seq,
		arg.ParentID,
	)
	return err
}
