// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ebooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accessibleAuthors = `-- name: AccessibleAuthors :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT ba.name, ba.sort_name FROM book_authors ba
JOIN books b ON b.id = ba.book_id
WHERE b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree)
ORDER BY ba.sort_name, ba.name
`

type AccessibleAuthorsRow struct {
	Name     string `json:"name"`
	SortName string `json:"sort_name"`
}

// Returns distinct authors with their sort_name for navigation, from accessible books.
// Both name and sort_name are selected so ORDER BY sort_name satisfies DISTINCT rules.
func (q *Queries) AccessibleAuthors(ctx context.Context, userID pgtype.UUID) ([]AccessibleAuthorsRow, error) {
	rows, err := q.db.Query(ctx, accessibleAuthors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessibleAuthorsRow{}
	for rows.Next() {
		var i AccessibleAuthorsRow
		if err := rows.Scan(&i.Name, &i.SortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBook = `-- name: AccessibleBook :one
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
WHERE b.id = $2
  AND (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
LIMIT 1
`

type AccessibleBookParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// Returns a single book by id if it is accessible to the user (own or shared).
func (q *Queries) AccessibleBook(ctx context.Context, arg AccessibleBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, accessibleBook, arg.UserID, arg.ID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Title,
		&i.SortTitle,
		&i.Language,
		&i.Isbn,
		&i.Description,
		&i.Publisher,
		&i.PublishedDate,
		&i.Series,
		&i.SeriesIndex,
		&i.Format,
		&i.ContentType,
		&i.Size,
		&i.CoverPath,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.MetadataEdited,
	)
	return i, err
}

const accessibleBookGenres = `-- name: AccessibleBookGenres :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT bt.tag FROM book_tags bt
JOIN books b ON b.id = bt.book_id
WHERE b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree)
ORDER BY bt.tag
`

// Returns distinct genre/tag values from accessible books, ordered alphabetically.
func (q *Queries) AccessibleBookGenres(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, accessibleBookGenres, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBooksAll = `-- name: AccessibleBooksAll :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
WHERE b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree)
ORDER BY b.sort_title, b.title
LIMIT $2 OFFSET $3
`

type AccessibleBooksAllParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Returns all books accessible to a user, ordered by sort_title, with pagination.
func (q *Queries) AccessibleBooksAll(ctx context.Context, arg AccessibleBooksAllParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, accessibleBooksAll, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBooksByAuthor = `-- name: AccessibleBooksByAuthor :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
JOIN book_authors ba ON ba.book_id = b.id
WHERE ba.name = $2
  AND (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
ORDER BY b.sort_title, b.title
LIMIT $3 OFFSET $4
`

type AccessibleBooksByAuthorParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Returns books accessible to a user filtered by author name.
func (q *Queries) AccessibleBooksByAuthor(ctx context.Context, arg AccessibleBooksByAuthorParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, accessibleBooksByAuthor,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBooksByGenre = `-- name: AccessibleBooksByGenre :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
JOIN book_tags bt ON bt.book_id = b.id
WHERE bt.tag = $2
  AND (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
ORDER BY b.sort_title, b.title
LIMIT $3 OFFSET $4
`

type AccessibleBooksByGenreParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Tag    string      `json:"tag"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Returns books accessible to a user filtered by genre/tag.
func (q *Queries) AccessibleBooksByGenre(ctx context.Context, arg AccessibleBooksByGenreParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, accessibleBooksByGenre,
		arg.UserID,
		arg.Tag,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBooksBySeries = `-- name: AccessibleBooksBySeries :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
WHERE b.series = $2
  AND (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
ORDER BY b.series_index, b.sort_title
LIMIT $3 OFFSET $4
`

type AccessibleBooksBySeriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Series pgtype.Text `json:"series"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Returns books accessible to a user for a given series, ordered by series_index.
func (q *Queries) AccessibleBooksBySeries(ctx context.Context, arg AccessibleBooksBySeriesParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, accessibleBooksBySeries,
		arg.UserID,
		arg.Series,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleBooksNewest = `-- name: AccessibleBooksNewest :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
WHERE b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree)
ORDER BY b.added_at DESC
LIMIT $2 OFFSET $3
`

type AccessibleBooksNewestParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Returns recently added books accessible to a user, newest first.
func (q *Queries) AccessibleBooksNewest(ctx context.Context, arg AccessibleBooksNewestParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, accessibleBooksNewest, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleSeries = `-- name: AccessibleSeries :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT b.series FROM books b
WHERE b.series IS NOT NULL AND b.series != ''
  AND (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
ORDER BY b.series
`

// Returns distinct series names from accessible books, ordered alphabetically.
func (q *Queries) AccessibleSeries(ctx context.Context, userID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, accessibleSeries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var series pgtype.Text
		if err := rows.Scan(&series); err != nil {
			return nil, err
		}
		items = append(items, series)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookAuthors = `-- name: BookAuthors :many
SELECT name, sort_name FROM book_authors WHERE book_id = $1 ORDER BY sort_name, name
`

type BookAuthorsRow struct {
	Name     string `json:"name"`
	SortName string `json:"sort_name"`
}

func (q *Queries) BookAuthors(ctx context.Context, bookID pgtype.UUID) ([]BookAuthorsRow, error) {
	rows, err := q.db.Query(ctx, bookAuthors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookAuthorsRow{}
	for rows.Next() {
		var i BookAuthorsRow
		if err := rows.Scan(&i.Name, &i.SortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookTags = `-- name: BookTags :many
SELECT tag FROM book_tags WHERE book_id = $1 ORDER BY tag
`

func (q *Queries) BookTags(ctx context.Context, bookID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, bookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearBookAuthors = `-- name: ClearBookAuthors :exec
DELETE FROM book_authors WHERE book_id = $1
`

func (q *Queries) ClearBookAuthors(ctx context.Context, bookID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBookAuthors, bookID)
	return err
}

const clearBookTags = `-- name: ClearBookTags :exec
DELETE FROM book_tags WHERE book_id = $1
`

func (q *Queries) ClearBookTags(ctx context.Context, bookID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBookTags, bookID)
	return err
}

const clearEbookCredentials = `-- name: ClearEbookCredentials :exec
UPDATE ebook_settings SET password_cipher = NULL, api_key = NULL, updated_at = now()
WHERE user_id = $1
`

func (q *Queries) ClearEbookCredentials(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearEbookCredentials, userID)
	return err
}

const countAccessibleBooks = `-- name: CountAccessibleBooks :one
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT COUNT(*) FROM books b
WHERE b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree)
`

// Returns the total count of books accessible to a user.
func (q *Queries) CountAccessibleBooks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleBooks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBookByNode = `-- name: DeleteBookByNode :exec
DELETE FROM books WHERE node_id = $1
`

func (q *Queries) DeleteBookByNode(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookByNode, nodeID)
	return err
}

const enabledEbookUsers = `-- name: EnabledEbookUsers :many
SELECT user_id, folder_node_id FROM ebook_settings WHERE enabled = true AND folder_node_id IS NOT NULL
`

type EnabledEbookUsersRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	FolderNodeID pgtype.UUID `json:"folder_node_id"`
}

func (q *Queries) EnabledEbookUsers(ctx context.Context) ([]EnabledEbookUsersRow, error) {
	rows, err := q.db.Query(ctx, enabledEbookUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnabledEbookUsersRow{}
	for rows.Next() {
		var i EnabledEbookUsersRow
		if err := rows.Scan(&i.UserID, &i.FolderNodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByNode = `-- name: GetBookByNode :one
SELECT id, user_id, node_id, title, sort_title, language, isbn, description, publisher, published_date, series, series_index, format, content_type, size, cover_path, added_at, updated_at, metadata_edited FROM books WHERE node_id = $1
`

func (q *Queries) GetBookByNode(ctx context.Context, nodeID pgtype.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByNode, nodeID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Title,
		&i.SortTitle,
		&i.Language,
		&i.Isbn,
		&i.Description,
		&i.Publisher,
		&i.PublishedDate,
		&i.Series,
		&i.SeriesIndex,
		&i.Format,
		&i.ContentType,
		&i.Size,
		&i.CoverPath,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.MetadataEdited,
	)
	return i, err
}

const getEbookSettings = `-- name: GetEbookSettings :one
SELECT user_id, enabled, folder_node_id, password_cipher, api_key, created_at, updated_at FROM ebook_settings WHERE user_id = $1
`

func (q *Queries) GetEbookSettings(ctx context.Context, userID pgtype.UUID) (EbookSetting, error) {
	row := q.db.QueryRow(ctx, getEbookSettings, userID)
	var i EbookSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.FolderNodeID,
		&i.PasswordCipher,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEbookSettingsByApiKey = `-- name: GetEbookSettingsByApiKey :one
SELECT user_id, enabled, folder_node_id, password_cipher, api_key, created_at, updated_at FROM ebook_settings WHERE api_key = $1
`

func (q *Queries) GetEbookSettingsByApiKey(ctx context.Context, apiKey pgtype.Text) (EbookSetting, error) {
	row := q.db.QueryRow(ctx, getEbookSettingsByApiKey, apiKey)
	var i EbookSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.FolderNodeID,
		&i.PasswordCipher,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookAuthor = `-- name: InsertBookAuthor :exec
INSERT INTO book_authors (book_id, name, sort_name) VALUES ($1, $2, $3)
ON CONFLICT (book_id, name) DO UPDATE SET sort_name = EXCLUDED.sort_name
`

type InsertBookAuthorParams struct {
	BookID   pgtype.UUID `json:"book_id"`
	Name     string      `json:"name"`
	SortName string      `json:"sort_name"`
}

func (q *Queries) InsertBookAuthor(ctx context.Context, arg InsertBookAuthorParams) error {
	_, err := q.db.Exec(ctx, insertBookAuthor, arg.BookID, arg.Name, arg.SortName)
	return err
}

const insertBookTag = `-- name: InsertBookTag :exec
INSERT INTO book_tags (book_id, tag) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertBookTagParams struct {
	BookID pgtype.UUID `json:"book_id"`
	Tag    string      `json:"tag"`
}

func (q *Queries) InsertBookTag(ctx context.Context, arg InsertBookTagParams) error {
	_, err := q.db.Exec(ctx, insertBookTag, arg.BookID, arg.Tag)
	return err
}

const searchAccessibleBooks = `-- name: SearchAccessibleBooks :many
WITH RECURSIVE shared_subtree AS (
    SELECT resource_id AS node_id FROM resource_shares
    WHERE resource_type = 'file_node' AND shared_with_user = $1
      AND (expires_at IS NULL OR expires_at > now())
    UNION
    SELECT n.id FROM nodes n JOIN shared_subtree st ON n.parent_id = st.node_id
)
SELECT DISTINCT b.id, b.user_id, b.node_id, b.title, b.sort_title, b.language, b.isbn, b.description, b.publisher, b.published_date, b.series, b.series_index, b.format, b.content_type, b.size, b.cover_path, b.added_at, b.updated_at, b.metadata_edited FROM books b
LEFT JOIN book_authors ba ON ba.book_id = b.id
WHERE (b.user_id = $1 OR b.node_id IN (SELECT node_id FROM shared_subtree))
  AND (
    b.title  ILIKE '%' || $2 || '%' OR
    ba.name  ILIKE '%' || $2 || '%' OR
    b.series ILIKE '%' || $2 || '%'
  )
ORDER BY b.sort_title, b.title
LIMIT $3 OFFSET $4
`

type SearchAccessibleBooksParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// Returns accessible books matching a case-insensitive substring in title, author, or series.
func (q *Queries) SearchAccessibleBooks(ctx context.Context, arg SearchAccessibleBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchAccessibleBooks,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Title,
			&i.SortTitle,
			&i.Language,
			&i.Isbn,
			&i.Description,
			&i.Publisher,
			&i.PublishedDate,
			&i.Series,
			&i.SeriesIndex,
			&i.Format,
			&i.ContentType,
			&i.Size,
			&i.CoverPath,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.MetadataEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookCoverPath = `-- name: SetBookCoverPath :exec
UPDATE books SET cover_path = $2 WHERE id = $1
`

type SetBookCoverPathParams struct {
	ID        pgtype.UUID `json:"id"`
	CoverPath pgtype.Text `json:"cover_path"`
}

func (q *Queries) SetBookCoverPath(ctx context.Context, arg SetBookCoverPathParams) error {
	_, err := q.db.Exec(ctx, setBookCoverPath, arg.ID, arg.CoverPath)
	return err
}

const setBookMetadataEdited = `-- name: SetBookMetadataEdited :exec
UPDATE books SET metadata_edited = $2, updated_at = now()
WHERE id = $1
`

type SetBookMetadataEditedParams struct {
	ID             pgtype.UUID `json:"id"`
	MetadataEdited bool        `json:"metadata_edited"`
}

func (q *Queries) SetBookMetadataEdited(ctx context.Context, arg SetBookMetadataEditedParams) error {
	_, err := q.db.Exec(ctx, setBookMetadataEdited, arg.ID, arg.MetadataEdited)
	return err
}

const setEbookCredentials = `-- name: SetEbookCredentials :exec
UPDATE ebook_settings SET password_cipher = $2, api_key = $3, updated_at = now()
WHERE user_id = $1
`

type SetEbookCredentialsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	PasswordCipher pgtype.Text `json:"password_cipher"`
	ApiKey         pgtype.Text `json:"api_key"`
}

func (q *Queries) SetEbookCredentials(ctx context.Context, arg SetEbookCredentialsParams) error {
	_, err := q.db.Exec(ctx, setEbookCredentials, arg.UserID, arg.PasswordCipher, arg.ApiKey)
	return err
}

const updateBookMetadata = `-- name: UpdateBookMetadata :exec
UPDATE books SET
    title = $3,
    sort_title = $4,
    language = $5,
    description = $6,
    publisher = $7,
    published_date = $8,
    series = $9,
    series_index = $10,
    metadata_edited = true,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateBookMetadataParams struct {
	ID            pgtype.UUID   `json:"id"`
	UserID        pgtype.UUID   `json:"user_id"`
	Title         string        `json:"title"`
	SortTitle     string        `json:"sort_title"`
	Language      pgtype.Text   `json:"language"`
	Description   pgtype.Text   `json:"description"`
	Publisher     pgtype.Text   `json:"publisher"`
	PublishedDate pgtype.Text   `json:"published_date"`
	Series        pgtype.Text   `json:"series"`
	SeriesIndex   pgtype.Float4 `json:"series_index"`
}

func (q *Queries) UpdateBookMetadata(ctx context.Context, arg UpdateBookMetadataParams) error {
	_, err := q.db.Exec(ctx, updateBookMetadata,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.SortTitle,
		arg.Language,
		arg.Description,
		arg.Publisher,
		arg.PublishedDate,
		arg.Series,
		arg.SeriesIndex,
	)
	return err
}

const upsertBook = `-- name: UpsertBook :one
INSERT INTO books (user_id, node_id, title, sort_title, language, isbn, description, publisher,
    published_date, series, series_index, format, content_type, size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (node_id) DO UPDATE SET
    user_id        = EXCLUDED.user_id,
    title          = EXCLUDED.title,
    sort_title     = EXCLUDED.sort_title,
    language       = EXCLUDED.language,
    isbn           = EXCLUDED.isbn,
    description    = EXCLUDED.description,
    publisher      = EXCLUDED.publisher,
    published_date = EXCLUDED.published_date,
    series         = EXCLUDED.series,
    series_index   = EXCLUDED.series_index,
    format         = EXCLUDED.format,
    content_type   = EXCLUDED.content_type,
    size           = EXCLUDED.size,
    updated_at     = now()
RETURNING id, user_id, node_id, title, sort_title, language, isbn, description, publisher, published_date, series, series_index, format, content_type, size, cover_path, added_at, updated_at, metadata_edited
`

type UpsertBookParams struct {
	UserID        pgtype.UUID   `json:"user_id"`
	NodeID        pgtype.UUID   `json:"node_id"`
	Title         string        `json:"title"`
	SortTitle     string        `json:"sort_title"`
	Language      pgtype.Text   `json:"language"`
	Isbn          pgtype.Text   `json:"isbn"`
	Description   pgtype.Text   `json:"description"`
	Publisher     pgtype.Text   `json:"publisher"`
	PublishedDate pgtype.Text   `json:"published_date"`
	Series        pgtype.Text   `json:"series"`
	SeriesIndex   pgtype.Float4 `json:"series_index"`
	Format        string        `json:"format"`
	ContentType   string        `json:"content_type"`
	Size          pgtype.Int8   `json:"size"`
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, upsertBook,
		arg.UserID,
		arg.NodeID,
		arg.Title,
		arg.SortTitle,
		arg.Language,
		arg.Isbn,
		arg.Description,
		arg.Publisher,
		arg.PublishedDate,
		arg.Series,
		arg.SeriesIndex,
		arg.Format,
		arg.ContentType,
		arg.Size,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Title,
		&i.SortTitle,
		&i.Language,
		&i.Isbn,
		&i.Description,
		&i.Publisher,
		&i.PublishedDate,
		&i.Series,
		&i.SeriesIndex,
		&i.Format,
		&i.ContentType,
		&i.Size,
		&i.CoverPath,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.MetadataEdited,
	)
	return i, err
}

const upsertEbookSettings = `-- name: UpsertEbookSettings :one
INSERT INTO ebook_settings (user_id, enabled, folder_node_id, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET enabled = EXCLUDED.enabled,
    folder_node_id = EXCLUDED.folder_node_id, updated_at = now()
RETURNING user_id, enabled, folder_node_id, password_cipher, api_key, created_at, updated_at
`

type UpsertEbookSettingsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Enabled      bool        `json:"enabled"`
	FolderNodeID pgtype.UUID `json:"folder_node_id"`
}

func (q *Queries) UpsertEbookSettings(ctx context.Context, arg UpsertEbookSettingsParams) (EbookSetting, error) {
	row := q.db.QueryRow(ctx, upsertEbookSettings, arg.UserID, arg.Enabled, arg.FolderNodeID)
	var i EbookSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.FolderNodeID,
		&i.PasswordCipher,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
