// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kosync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT user_id, document, progress, percentage, device, device_id, updated_at FROM reading_progress WHERE user_id = $1 AND document = $2
`

type GetReadingProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Document string      `json:"document"`
}

// Returns the stored reading position for (user_id, document).
func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.Document)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.Document,
		&i.Progress,
		&i.Percentage,
		&i.Device,
		&i.DeviceID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
INSERT INTO reading_progress (user_id, document, progress, percentage, device, device_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, document) DO UPDATE SET
    progress   = EXCLUDED.progress,
    percentage = EXCLUDED.percentage,
    device     = EXCLUDED.device,
    device_id  = EXCLUDED.device_id,
    updated_at = now()
RETURNING user_id, document, progress, percentage, device, device_id, updated_at
`

type UpsertReadingProgressParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Document   string      `json:"document"`
	Progress   string      `json:"progress"`
	Percentage float32     `json:"percentage"`
	Device     string      `json:"device"`
	DeviceID   string      `json:"device_id"`
}

// Inserts or updates the reading position for (user_id, document). All mutable
// fields are refreshed on conflict so the latest device wins.
func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, upsertReadingProgress,
		arg.UserID,
		arg.Document,
		arg.Progress,
		arg.Percentage,
		arg.Device,
		arg.DeviceID,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.Document,
		&i.Progress,
		&i.Percentage,
		&i.Device,
		&i.DeviceID,
		&i.UpdatedAt,
	)
	return i, err
}
