// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Addressbook struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Uri       string             `json:"uri"`
	Name      string             `json:"name"`
	Ctag      int64              `json:"ctag"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AddressbookObject struct {
	ID            pgtype.UUID        `json:"id"`
	AddressbookID pgtype.UUID        `json:"addressbook_id"`
	Uid           string             `json:"uid"`
	Data          string             `json:"data"`
	Etag          string             `json:"etag"`
	Parsed        []byte             `json:"parsed"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Album struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Name          string             `json:"name"`
	Year          pgtype.Int4        `json:"year"`
	Genre         pgtype.Text        `json:"genre"`
	CoverArt      pgtype.Text        `json:"cover_art"`
	SongCount     int32              `json:"song_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	MusicbrainzID pgtype.Text        `json:"musicbrainz_id"`
}

type Artist struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	Name          string      `json:"name"`
	SortName      string      `json:"sort_name"`
	CoverArt      pgtype.Text `json:"cover_art"`
	MusicbrainzID pgtype.Text `json:"musicbrainz_id"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Event     string             `json:"event"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BackupCode struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Book struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	Title          string             `json:"title"`
	SortTitle      string             `json:"sort_title"`
	Language       pgtype.Text        `json:"language"`
	Isbn           pgtype.Text        `json:"isbn"`
	Description    pgtype.Text        `json:"description"`
	Publisher      pgtype.Text        `json:"publisher"`
	PublishedDate  pgtype.Text        `json:"published_date"`
	Series         pgtype.Text        `json:"series"`
	SeriesIndex    pgtype.Float4      `json:"series_index"`
	Format         string             `json:"format"`
	ContentType    string             `json:"content_type"`
	Size           pgtype.Int8        `json:"size"`
	CoverPath      pgtype.Text        `json:"cover_path"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	MetadataEdited bool               `json:"metadata_edited"`
}

type BookAuthor struct {
	BookID   pgtype.UUID `json:"book_id"`
	Name     string      `json:"name"`
	SortName string      `json:"sort_name"`
}

type BookTag struct {
	BookID pgtype.UUID `json:"book_id"`
	Tag    string      `json:"tag"`
}

type Bookmark struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ItemID     pgtype.UUID        `json:"item_id"`
	ItemType   string             `json:"item_type"`
	PositionMs int64              `json:"position_ms"`
	Comment    string             `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
}

type Calendar struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Uri        string             `json:"uri"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	Ctag       int64              `json:"ctag"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Components string             `json:"components"`
}

type CalendarObject struct {
	ID         pgtype.UUID        `json:"id"`
	CalendarID pgtype.UUID        `json:"calendar_id"`
	Uid        string             `json:"uid"`
	Data       string             `json:"data"`
	Etag       string             `json:"etag"`
	Parsed     []byte             `json:"parsed"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ChangeLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	NodeID    pgtype.UUID        `json:"node_id"`
	Seq       int64              `json:"seq"`
	Op        string             `json:"op"`
	Version   int64              `json:"version"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	SecretHash pgtype.Text        `json:"secret_hash"`
	TokenHash  pgtype.Text        `json:"token_hash"`
}

type DevicePairing struct {
	ID             pgtype.UUID        `json:"id"`
	DeviceCodeHash string             `json:"device_code_hash"`
	UserCode       string             `json:"user_code"`
	ProposedName   string             `json:"proposed_name"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	UserID         pgtype.UUID        `json:"user_id"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type EbookSetting struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Enabled        bool               `json:"enabled"`
	FolderNodeID   pgtype.UUID        `json:"folder_node_id"`
	PasswordCipher pgtype.Text        `json:"password_cipher"`
	ApiKey         pgtype.Text        `json:"api_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FileVersion struct {
	ID              pgtype.UUID        `json:"id"`
	NodeID          pgtype.UUID        `json:"node_id"`
	Version         int64              `json:"version"`
	ContentHash     pgtype.Text        `json:"content_hash"`
	DiskPath        pgtype.Text        `json:"disk_path"`
	Size            pgtype.Int8        `json:"size"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	IsConflictLoser bool               `json:"is_conflict_loser"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InternetRadioStation struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	StreamUrl   string             `json:"stream_url"`
	HomepageUrl string             `json:"homepage_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type KnownLogin struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Fingerprint string             `json:"fingerprint"`
	UserAgent   string             `json:"user_agent"`
	Ip          string             `json:"ip"`
	FirstSeen   pgtype.Timestamptz `json:"first_seen"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

type MusicSetting struct {
	UserID            pgtype.UUID        `json:"user_id"`
	Enabled           bool               `json:"enabled"`
	FolderNodeID      pgtype.UUID        `json:"folder_node_id"`
	PasswordCipher    pgtype.Text        `json:"password_cipher"`
	ApiKey            pgtype.Text        `json:"api_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TagEditVersioning bool               `json:"tag_edit_versioning"`
}

type Node struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Name            string             `json:"name"`
	IsDir           bool               `json:"is_dir"`
	Size            pgtype.Int8        `json:"size"`
	ContentHash     pgtype.Text        `json:"content_hash"`
	DiskPath        pgtype.Text        `json:"disk_path"`
	Mime            pgtype.Text        `json:"mime"`
	IsVault         bool               `json:"is_vault"`
	Version         int64              `json:"version"`
	ModifiedAt      pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	IsConflictLoser bool               `json:"is_conflict_loser"`
	ConflictOf      pgtype.UUID        `json:"conflict_of"`
}

type NotificationPref struct {
	UserID   pgtype.UUID `json:"user_id"`
	EventKey string      `json:"event_key"`
	Channel  string      `json:"channel"`
	Enabled  bool        `json:"enabled"`
}

type PlayHistory struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	SongID   pgtype.UUID        `json:"song_id"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

type PlayQueue struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CurrentID  pgtype.UUID        `json:"current_id"`
	PositionMs int64              `json:"position_ms"`
	ChangedBy  string             `json:"changed_by"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
}

type PlayQueueEntry struct {
	UserID pgtype.UUID `json:"user_id"`
	Idx    int32       `json:"idx"`
	SongID pgtype.UUID `json:"song_id"`
}

type Playlist struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Comment   string             `json:"comment"`
	Public    bool               `json:"public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type PlaylistSong struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	SongID     pgtype.UUID `json:"song_id"`
	Position   int32       `json:"position"`
}

type PodcastChannel struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	FeedUrl       string             `json:"feed_url"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	CoverUrl      string             `json:"cover_url"`
	CoverPath     pgtype.Text        `json:"cover_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastFetchedAt pgtype.Timestamptz `json:"last_fetched_at"`
}

type PodcastEpisode struct {
	ID          pgtype.UUID        `json:"id"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PubDate     pgtype.Timestamptz `json:"pub_date"`
	AudioUrl    string             `json:"audio_url"`
	Duration    pgtype.Int4        `json:"duration"`
	Suffix      string             `json:"suffix"`
	ContentType string             `json:"content_type"`
	Size        pgtype.Int8        `json:"size"`
	Status      string             `json:"status"`
	DiskPath    pgtype.Text        `json:"disk_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Rating struct {
	UserID   pgtype.UUID `json:"user_id"`
	ItemID   pgtype.UUID `json:"item_id"`
	ItemType string      `json:"item_type"`
	Rating   int32       `json:"rating"`
}

type ReadingProgress struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Document   string             `json:"document"`
	Progress   string             `json:"progress"`
	Percentage float32            `json:"percentage"`
	Device     string             `json:"device"`
	DeviceID   string             `json:"device_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ResourceShare struct {
	ID                pgtype.UUID        `json:"id"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        pgtype.UUID        `json:"resource_id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	SharedWithUser    pgtype.UUID        `json:"shared_with_user"`
	ShareLinkToken    pgtype.Text        `json:"share_link_token"`
	Access            string             `json:"access"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SharePasswordHash pgtype.Text        `json:"share_password_hash"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	IsSecret  bool               `json:"is_secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type Song struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	AlbumID       pgtype.UUID        `json:"album_id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	NodeID        pgtype.UUID        `json:"node_id"`
	Title         string             `json:"title"`
	Track         pgtype.Int4        `json:"track"`
	Disc          pgtype.Int4        `json:"disc"`
	Duration      pgtype.Int4        `json:"duration"`
	Bitrate       pgtype.Int4        `json:"bitrate"`
	Suffix        pgtype.Text        `json:"suffix"`
	ContentType   pgtype.Text        `json:"content_type"`
	Size          pgtype.Int8        `json:"size"`
	Genre         pgtype.Text        `json:"genre"`
	MusicbrainzID pgtype.Text        `json:"musicbrainz_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Star struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	ItemType  string             `json:"item_type"`
	StarredAt pgtype.Timestamptz `json:"starred_at"`
}

type SyncSetting struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Enabled      bool               `json:"enabled"`
	FolderNodeID pgtype.UUID        `json:"folder_node_id"`
	Epoch        int64              `json:"epoch"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	StorageQuota       pgtype.Int8        `json:"storage_quota"`
	StorageUsed        int64              `json:"storage_used"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Role               string             `json:"role"`
	ChangeSeq          int64              `json:"change_seq"`
	QuotaNotifiedAt    pgtype.Timestamptz `json:"quota_notified_at"`
	TokenVersion       int64              `json:"token_version"`
	Language           string             `json:"language"`
	MustChangePassword bool               `json:"must_change_password"`
}

type UserTotp struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Secret      string             `json:"secret"`
	Enabled     bool               `json:"enabled"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WebauthnCredential struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CredentialID []byte             `json:"credential_id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	Credential   []byte             `json:"credential"`
}
