// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addressbookShareForUser = `-- name: AddressbookShareForUser :one
SELECT id FROM resource_shares
WHERE resource_type = 'addressbook' AND resource_id = $1
  AND shared_with_user = $2 AND (expires_at IS NULL OR expires_at > now())
LIMIT 1
`

type AddressbookShareForUserParams struct {
	ResourceID     pgtype.UUID `json:"resource_id"`
	SharedWithUser pgtype.UUID `json:"shared_with_user"`
}

func (q *Queries) AddressbookShareForUser(ctx context.Context, arg AddressbookShareForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addressbookShareForUser, arg.ResourceID, arg.SharedWithUser)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const appendChange = `-- name: AppendChange :one
INSERT INTO change_log (user_id, node_id, seq, op, version, device_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, node_id, seq, op, version, device_id, created_at
`

type AppendChangeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	NodeID   pgtype.UUID `json:"node_id"`
	Seq      int64       `json:"seq"`
	Op       string      `json:"op"`
	Version  int64       `json:"version"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) AppendChange(ctx context.Context, arg AppendChangeParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, appendChange,
		arg.UserID,
		arg.NodeID,
		arg.Seq,
		arg.Op,
		arg.Version,
		arg.DeviceID,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Seq,
		&i.Op,
		&i.Version,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const approvePairing = `-- name: ApprovePairing :one
UPDATE device_pairings SET status = 'approved', user_id = $2, device_id = $3
WHERE id = $1 AND status = 'pending'
RETURNING id
`

type ApprovePairingParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) ApprovePairing(ctx context.Context, arg ApprovePairingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, approvePairing, arg.ID, arg.UserID, arg.DeviceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const availableMFAFactors = `-- name: AvailableMFAFactors :one
SELECT
    EXISTS(SELECT 1 FROM user_totp ut WHERE ut.user_id = $1 AND ut.enabled) AS has_totp,
    EXISTS(SELECT 1 FROM webauthn_credentials wc WHERE wc.user_id = $1) AS has_webauthn
`

type AvailableMFAFactorsRow struct {
	HasTotp     bool `json:"has_totp"`
	HasWebauthn bool `json:"has_webauthn"`
}

// Which interactive second factors the user has. Used by Login to branch.
func (q *Queries) AvailableMFAFactors(ctx context.Context, userID pgtype.UUID) (AvailableMFAFactorsRow, error) {
	row := q.db.QueryRow(ctx, availableMFAFactors, userID)
	var i AvailableMFAFactorsRow
	err := row.Scan(&i.HasTotp, &i.HasWebauthn)
	return i, err
}

const bumpAddressbookCtag = `-- name: BumpAddressbookCtag :exec
UPDATE addressbooks SET ctag = ctag + 1 WHERE id = $1
`

func (q *Queries) BumpAddressbookCtag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpAddressbookCtag, id)
	return err
}

const bumpCalendarCtag = `-- name: BumpCalendarCtag :exec
UPDATE calendars SET ctag = ctag + 1 WHERE id = $1
`

func (q *Queries) BumpCalendarCtag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpCalendarCtag, id)
	return err
}

const bumpNodeVersion = `-- name: BumpNodeVersion :one
UPDATE nodes SET version = version + 1, modified_at = now() WHERE id = $1 RETURNING version
`

func (q *Queries) BumpNodeVersion(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpNodeVersion, id)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const calendarShareForUser = `-- name: CalendarShareForUser :one
SELECT id FROM resource_shares
WHERE resource_type = 'calendar' AND resource_id = $1
  AND shared_with_user = $2 AND (expires_at IS NULL OR expires_at > now())
LIMIT 1
`

type CalendarShareForUserParams struct {
	ResourceID     pgtype.UUID `json:"resource_id"`
	SharedWithUser pgtype.UUID `json:"shared_with_user"`
}

// A user's access level to a file_node, accounting for inheritance: we check
// the node itself AND all its ancestors (recursive CTE), taking active shares for the user.
func (q *Queries) CalendarShareForUser(ctx context.Context, arg CalendarShareForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, calendarShareForUser, arg.ResourceID, arg.SharedWithUser)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const clearQuotaNotified = `-- name: ClearQuotaNotified :exec
UPDATE users SET quota_notified_at = NULL
WHERE storage_quota IS NOT NULL
  AND storage_used * 10 < storage_quota * 9
  AND quota_notified_at IS NOT NULL
`

func (q *Queries) ClearQuotaNotified(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearQuotaNotified)
	return err
}

const confirmUserTOTP = `-- name: ConfirmUserTOTP :exec
UPDATE user_totp SET enabled = true, confirmed_at = now() WHERE user_id = $1
`

func (q *Queries) ConfirmUserTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmUserTOTP, userID)
	return err
}

const consumePairingIfApproved = `-- name: ConsumePairingIfApproved :one
UPDATE device_pairings SET status = 'consumed'
WHERE id = $1 AND status = 'approved'
RETURNING id
`

// Atomically "claim" an approved pairing: a race between two polls → token exactly once.
func (q *Queries) ConsumePairingIfApproved(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumePairingIfApproved, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const countAddressbooks = `-- name: CountAddressbooks :one
SELECT count(*) FROM addressbooks WHERE user_id = $1
`

func (q *Queries) CountAddressbooks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressbooks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCalendars = `-- name: CountCalendars :one
SELECT count(*) FROM calendars WHERE user_id = $1
`

func (q *Queries) CountCalendars(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCalendars, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserLogins = `-- name: CountUserLogins :one
SELECT count(*) FROM known_logins WHERE user_id = $1
`

func (q *Queries) CountUserLogins(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLogins, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddressbook = `-- name: CreateAddressbook :one
INSERT INTO addressbooks (user_id, uri, name) VALUES ($1, $2, $3) RETURNING id, user_id, uri, name, ctag, created_at
`

type CreateAddressbookParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Uri    string      `json:"uri"`
	Name   string      `json:"name"`
}

// == addressbooks ==
func (q *Queries) CreateAddressbook(ctx context.Context, arg CreateAddressbookParams) (Addressbook, error) {
	row := q.db.QueryRow(ctx, createAddressbook, arg.UserID, arg.Uri, arg.Name)
	var i Addressbook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Ctag,
		&i.CreatedAt,
	)
	return i, err
}

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (user_id, uri, name, color) VALUES ($1, $2, $3, $4) RETURNING id, user_id, uri, name, color, ctag, created_at, components
`

type CreateCalendarParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Uri    string      `json:"uri"`
	Name   string      `json:"name"`
	Color  string      `json:"color"`
}

// == calendars ==
func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.UserID,
		arg.Uri,
		arg.Name,
		arg.Color,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Color,
		&i.Ctag,
		&i.CreatedAt,
		&i.Components,
	)
	return i, err
}

const createCalendarWithComponents = `-- name: CreateCalendarWithComponents :one
INSERT INTO calendars (user_id, uri, name, color, components) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, uri, name, color, ctag, created_at, components
`

type CreateCalendarWithComponentsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Uri        string      `json:"uri"`
	Name       string      `json:"name"`
	Color      string      `json:"color"`
	Components string      `json:"components"`
}

func (q *Queries) CreateCalendarWithComponents(ctx context.Context, arg CreateCalendarWithComponentsParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendarWithComponents,
		arg.UserID,
		arg.Uri,
		arg.Name,
		arg.Color,
		arg.Components,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Color,
		&i.Ctag,
		&i.CreatedAt,
		&i.Components,
	)
	return i, err
}

const createConflictNode = `-- name: CreateConflictNode :one
INSERT INTO nodes (
    user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime,
    is_conflict_loser, conflict_of
) VALUES ($1, $2, $3, false, $4, $5, $6, $7, true, $8)
RETURNING id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of
`

type CreateConflictNodeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Size        pgtype.Int8 `json:"size"`
	ContentHash pgtype.Text `json:"content_hash"`
	DiskPath    pgtype.Text `json:"disk_path"`
	Mime        pgtype.Text `json:"mime"`
	ConflictOf  pgtype.UUID `json:"conflict_of"`
}

// A conflict copy is a separate file node.
func (q *Queries) CreateConflictNode(ctx context.Context, arg CreateConflictNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createConflictNode,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.Size,
		arg.ContentHash,
		arg.DiskPath,
		arg.Mime,
		arg.ConflictOf,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const createDesktopDevice = `-- name: CreateDesktopDevice :one
INSERT INTO devices (user_id, name, kind) VALUES ($1, $2, 'desktop')
RETURNING id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash
`

type CreateDesktopDeviceParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateDesktopDevice(ctx context.Context, arg CreateDesktopDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDesktopDevice, arg.UserID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretHash,
		&i.TokenHash,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, kind)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash
`

type CreateDeviceParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Kind   string      `json:"kind"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name, arg.Kind)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretHash,
		&i.TokenHash,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
    user_id, parent_id, name, is_dir, size,
    content_hash, disk_path, mime, is_vault, modified_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of
`

type CreateNodeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	IsDir       bool        `json:"is_dir"`
	Size        pgtype.Int8 `json:"size"`
	ContentHash pgtype.Text `json:"content_hash"`
	DiskPath    pgtype.Text `json:"disk_path"`
	Mime        pgtype.Text `json:"mime"`
	IsVault     bool        `json:"is_vault"`
	ModifiedBy  pgtype.UUID `json:"modified_by"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.IsDir,
		arg.Size,
		arg.ContentHash,
		arg.DiskPath,
		arg.Mime,
		arg.IsVault,
		arg.ModifiedBy,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const createPairing = `-- name: CreatePairing :one

INSERT INTO device_pairings (device_code_hash, user_code, proposed_name, kind, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, device_code_hash, user_code, proposed_name, kind, status, user_id, device_id, created_at, expires_at
`

type CreatePairingParams struct {
	DeviceCodeHash string             `json:"device_code_hash"`
	UserCode       string             `json:"user_code"`
	ProposedName   string             `json:"proposed_name"`
	Kind           string             `json:"kind"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// Device pairing (device authorization flow, step 3.1.2).
func (q *Queries) CreatePairing(ctx context.Context, arg CreatePairingParams) (DevicePairing, error) {
	row := q.db.QueryRow(ctx, createPairing,
		arg.DeviceCodeHash,
		arg.UserCode,
		arg.ProposedName,
		arg.Kind,
		arg.ExpiresAt,
	)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCode,
		&i.ProposedName,
		&i.Kind,
		&i.Status,
		&i.UserID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createShare = `-- name: CreateShare :one
INSERT INTO resource_shares (
    resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash
`

type CreateShareParams struct {
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	SharedWithUser pgtype.UUID        `json:"shared_with_user"`
	ShareLinkToken pgtype.Text        `json:"share_link_token"`
	Access         string             `json:"access"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.ResourceType,
		arg.ResourceID,
		arg.OwnerID,
		arg.SharedWithUser,
		arg.ShareLinkToken,
		arg.Access,
		arg.ExpiresAt,
	)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OwnerID,
		&i.SharedWithUser,
		&i.ShareLinkToken,
		&i.Access,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SharePasswordHash,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name) VALUES ($1) RETURNING id, name, created_at
`

// Stage 0 base access layer. Queries are extended in steps 0.2–0.5.
func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, storage_quota, role, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, password_hash, storage_quota, storage_used, created_at, role, change_seq, quota_notified_at, token_version, language, must_change_password
`

type CreateUserParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	StorageQuota       pgtype.Int8 `json:"storage_quota"`
	Role               string      `json:"role"`
	MustChangePassword bool        `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.StorageQuota,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.Role,
		&i.ChangeSeq,
		&i.QuotaNotifiedAt,
		&i.TokenVersion,
		&i.Language,
		&i.MustChangePassword,
	)
	return i, err
}

const createWebdavDevice = `-- name: CreateWebdavDevice :one
INSERT INTO devices (user_id, name, kind, secret_hash)
VALUES ($1, $2, 'webdav', $3)
RETURNING id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash
`

type CreateWebdavDeviceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	SecretHash pgtype.Text `json:"secret_hash"`
}

func (q *Queries) CreateWebdavDevice(ctx context.Context, arg CreateWebdavDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createWebdavDevice, arg.UserID, arg.Name, arg.SecretHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretHash,
		&i.TokenHash,
	)
	return i, err
}

const deleteAddressbook = `-- name: DeleteAddressbook :exec
DELETE FROM addressbooks WHERE id = $1 AND user_id = $2
`

type DeleteAddressbookParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddressbook(ctx context.Context, arg DeleteAddressbookParams) error {
	_, err := q.db.Exec(ctx, deleteAddressbook, arg.ID, arg.UserID)
	return err
}

const deleteAddressbookObject = `-- name: DeleteAddressbookObject :execrows
DELETE FROM addressbook_objects WHERE addressbook_id = $1 AND uid = $2
`

type DeleteAddressbookObjectParams struct {
	AddressbookID pgtype.UUID `json:"addressbook_id"`
	Uid           string      `json:"uid"`
}

func (q *Queries) DeleteAddressbookObject(ctx context.Context, arg DeleteAddressbookObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddressbookObject, arg.AddressbookID, arg.Uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :exec
DELETE FROM backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	return err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars WHERE id = $1 AND user_id = $2
`

type DeleteCalendarParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error {
	_, err := q.db.Exec(ctx, deleteCalendar, arg.ID, arg.UserID)
	return err
}

const deleteCalendarObject = `-- name: DeleteCalendarObject :execrows
DELETE FROM calendar_objects WHERE calendar_id = $1 AND uid = $2
`

type DeleteCalendarObjectParams struct {
	CalendarID pgtype.UUID `json:"calendar_id"`
	Uid        string      `json:"uid"`
}

func (q *Queries) DeleteCalendarObject(ctx context.Context, arg DeleteCalendarObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalendarObject, arg.CalendarID, arg.Uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const deleteExpiredPairings = `-- name: DeleteExpiredPairings :exec
DELETE FROM device_pairings WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPairings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPairings)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM resource_shares WHERE id = $1
`

func (q *Queries) DeleteShare(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShare, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserTOTP = `-- name: DeleteUserTOTP :exec
DELETE FROM user_totp WHERE user_id = $1
`

func (q *Queries) DeleteUserTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTOTP, userID)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const getActiveShareByToken = `-- name: GetActiveShareByToken :one
SELECT id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash FROM resource_shares
WHERE share_link_token = $1::text
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveShareByToken(ctx context.Context, token string) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, getActiveShareByToken, token)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OwnerID,
		&i.SharedWithUser,
		&i.ShareLinkToken,
		&i.Access,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SharePasswordHash,
	)
	return i, err
}

const getAddressbook = `-- name: GetAddressbook :one
SELECT id, user_id, uri, name, ctag, created_at FROM addressbooks WHERE id = $1
`

func (q *Queries) GetAddressbook(ctx context.Context, id pgtype.UUID) (Addressbook, error) {
	row := q.db.QueryRow(ctx, getAddressbook, id)
	var i Addressbook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Ctag,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressbookByURI = `-- name: GetAddressbookByURI :one
SELECT id, user_id, uri, name, ctag, created_at FROM addressbooks WHERE uri = $1
`

func (q *Queries) GetAddressbookByURI(ctx context.Context, uri string) (Addressbook, error) {
	row := q.db.QueryRow(ctx, getAddressbookByURI, uri)
	var i Addressbook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Ctag,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressbookObject = `-- name: GetAddressbookObject :one
SELECT id, addressbook_id, uid, data, etag, parsed, created_at, updated_at FROM addressbook_objects WHERE addressbook_id = $1 AND uid = $2
`

type GetAddressbookObjectParams struct {
	AddressbookID pgtype.UUID `json:"addressbook_id"`
	Uid           string      `json:"uid"`
}

func (q *Queries) GetAddressbookObject(ctx context.Context, arg GetAddressbookObjectParams) (AddressbookObject, error) {
	row := q.db.QueryRow(ctx, getAddressbookObject, arg.AddressbookID, arg.Uid)
	var i AddressbookObject
	err := row.Scan(
		&i.ID,
		&i.AddressbookID,
		&i.Uid,
		&i.Data,
		&i.Etag,
		&i.Parsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendar = `-- name: GetCalendar :one
SELECT id, user_id, uri, name, color, ctag, created_at, components FROM calendars WHERE id = $1
`

func (q *Queries) GetCalendar(ctx context.Context, id pgtype.UUID) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendar, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Color,
		&i.Ctag,
		&i.CreatedAt,
		&i.Components,
	)
	return i, err
}

const getCalendarByURI = `-- name: GetCalendarByURI :one
SELECT id, user_id, uri, name, color, ctag, created_at, components FROM calendars WHERE uri = $1
`

func (q *Queries) GetCalendarByURI(ctx context.Context, uri string) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarByURI, uri)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uri,
		&i.Name,
		&i.Color,
		&i.Ctag,
		&i.CreatedAt,
		&i.Components,
	)
	return i, err
}

const getCalendarObject = `-- name: GetCalendarObject :one
SELECT id, calendar_id, uid, data, etag, parsed, created_at, updated_at FROM calendar_objects WHERE calendar_id = $1 AND uid = $2
`

type GetCalendarObjectParams struct {
	CalendarID pgtype.UUID `json:"calendar_id"`
	Uid        string      `json:"uid"`
}

func (q *Queries) GetCalendarObject(ctx context.Context, arg GetCalendarObjectParams) (CalendarObject, error) {
	row := q.db.QueryRow(ctx, getCalendarObject, arg.CalendarID, arg.Uid)
	var i CalendarObject
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.Data,
		&i.Etag,
		&i.Parsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash FROM devices WHERE id = $1
`

// Device by id (middleware verifies the device token is still live → instant revocation).
func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretHash,
		&i.TokenHash,
	)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash FROM devices WHERE token_hash = $1
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash pgtype.Text) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretHash,
		&i.TokenHash,
	)
	return i, err
}

const getFileVersion = `-- name: GetFileVersion :one
SELECT id, node_id, version, content_hash, disk_path, size, device_id, is_conflict_loser, created_at FROM file_versions WHERE node_id = $1 AND version = $2
`

type GetFileVersionParams struct {
	NodeID  pgtype.UUID `json:"node_id"`
	Version int64       `json:"version"`
}

func (q *Queries) GetFileVersion(ctx context.Context, arg GetFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, getFileVersion, arg.NodeID, arg.Version)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Version,
		&i.ContentHash,
		&i.DiskPath,
		&i.Size,
		&i.DeviceID,
		&i.IsConflictLoser,
		&i.CreatedAt,
	)
	return i, err
}

const getLiveNodeByPath = `-- name: GetLiveNodeByPath :one
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes
WHERE user_id = $1 AND disk_path = $2::text AND deleted_at IS NULL
`

type GetLiveNodeByPathParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Path   string      `json:"path"`
}

func (q *Queries) GetLiveNodeByPath(ctx context.Context, arg GetLiveNodeByPathParams) (Node, error) {
	row := q.db.QueryRow(ctx, getLiveNodeByPath, arg.UserID, arg.Path)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const getNodeForUser = `-- name: GetNodeForUser :one
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNodeForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetNodeForUser(ctx context.Context, arg GetNodeForUserParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeForUser, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const getPairingByCodeHash = `-- name: GetPairingByCodeHash :one
SELECT id, device_code_hash, user_code, proposed_name, kind, status, user_id, device_id, created_at, expires_at FROM device_pairings WHERE device_code_hash = $1
`

func (q *Queries) GetPairingByCodeHash(ctx context.Context, deviceCodeHash string) (DevicePairing, error) {
	row := q.db.QueryRow(ctx, getPairingByCodeHash, deviceCodeHash)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCode,
		&i.ProposedName,
		&i.Kind,
		&i.Status,
		&i.UserID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPairingByUserCode = `-- name: GetPairingByUserCode :one
SELECT id, device_code_hash, user_code, proposed_name, kind, status, user_id, device_id, created_at, expires_at FROM device_pairings WHERE user_code = $1
`

func (q *Queries) GetPairingByUserCode(ctx context.Context, userCode string) (DevicePairing, error) {
	row := q.db.QueryRow(ctx, getPairingByUserCode, userCode)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCode,
		&i.ProposedName,
		&i.Kind,
		&i.Status,
		&i.UserID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, is_secret, updated_at, updated_by FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getShare = `-- name: GetShare :one
SELECT id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash FROM resource_shares WHERE id = $1
`

func (q *Queries) GetShare(ctx context.Context, id pgtype.UUID) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, getShare, id)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OwnerID,
		&i.SharedWithUser,
		&i.ShareLinkToken,
		&i.Access,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SharePasswordHash,
	)
	return i, err
}

const getTrashedNodeForUser = `-- name: GetTrashedNodeForUser :one
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes WHERE id = $1 AND user_id = $2 AND deleted_at IS NOT NULL
`

type GetTrashedNodeForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTrashedNodeForUser(ctx context.Context, arg GetTrashedNodeForUserParams) (Node, error) {
	row := q.db.QueryRow(ctx, getTrashedNodeForUser, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, storage_quota, storage_used, created_at, role, change_seq, quota_notified_at, token_version, language, must_change_password FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.Role,
		&i.ChangeSeq,
		&i.QuotaNotifiedAt,
		&i.TokenVersion,
		&i.Language,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, storage_quota, storage_used, created_at, role, change_seq, quota_notified_at, token_version, language, must_change_password FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.Role,
		&i.ChangeSeq,
		&i.QuotaNotifiedAt,
		&i.TokenVersion,
		&i.Language,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserLanguage = `-- name: GetUserLanguage :one
SELECT language FROM users WHERE id = $1
`

func (q *Queries) GetUserLanguage(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserLanguage, id)
	var language string
	err := row.Scan(&language)
	return language, err
}

const getUserTOTP = `-- name: GetUserTOTP :one
SELECT user_id, secret, enabled, confirmed_at, created_at FROM user_totp WHERE user_id = $1
`

func (q *Queries) GetUserTOTP(ctx context.Context, userID pgtype.UUID) (UserTotp, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteNode = `-- name: HardDeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) HardDeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteNode, id)
	return err
}

const hardDeleteSubtree = `-- name: HardDeleteSubtree :exec
DELETE FROM nodes
WHERE user_id = $1
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
  AND deleted_at IS NOT NULL
`

type HardDeleteSubtreeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Prefix string      `json:"prefix"`
}

func (q *Queries) HardDeleteSubtree(ctx context.Context, arg HardDeleteSubtreeParams) error {
	_, err := q.db.Exec(ctx, hardDeleteSubtree, arg.UserID, arg.Prefix)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (user_id, event, ip, user_agent, detail) VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Event     string      `json:"event"`
	Ip        string      `json:"ip"`
	UserAgent string      `json:"user_agent"`
	Detail    []byte      `json:"detail"`
}

// Audit log (A.7).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Event,
		arg.Ip,
		arg.UserAgent,
		arg.Detail,
	)
	return err
}

const insertBackupCode = `-- name: InsertBackupCode :exec

INSERT INTO backup_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertBackupCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash string      `json:"code_hash"`
}

// Backup codes (A.3). One-time, argon2id-hashed.
func (q *Queries) InsertBackupCode(ctx context.Context, arg InsertBackupCodeParams) error {
	_, err := q.db.Exec(ctx, insertBackupCode, arg.UserID, arg.CodeHash)
	return err
}

const insertFileVersion = `-- name: InsertFileVersion :one
INSERT INTO file_versions (
    node_id, version, content_hash, disk_path, size, device_id, is_conflict_loser
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, node_id, version, content_hash, disk_path, size, device_id, is_conflict_loser, created_at
`

type InsertFileVersionParams struct {
	NodeID          pgtype.UUID `json:"node_id"`
	Version         int64       `json:"version"`
	ContentHash     pgtype.Text `json:"content_hash"`
	DiskPath        pgtype.Text `json:"disk_path"`
	Size            pgtype.Int8 `json:"size"`
	DeviceID        pgtype.UUID `json:"device_id"`
	IsConflictLoser bool        `json:"is_conflict_loser"`
}

func (q *Queries) InsertFileVersion(ctx context.Context, arg InsertFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, insertFileVersion,
		arg.NodeID,
		arg.Version,
		arg.ContentHash,
		arg.DiskPath,
		arg.Size,
		arg.DeviceID,
		arg.IsConflictLoser,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Version,
		&i.ContentHash,
		&i.DiskPath,
		&i.Size,
		&i.DeviceID,
		&i.IsConflictLoser,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :one

INSERT INTO webauthn_credentials (user_id, credential_id, credential, name)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, credential_id, name, created_at, last_used_at, credential
`

type InsertWebAuthnCredentialParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CredentialID []byte      `json:"credential_id"`
	Credential   []byte      `json:"credential"`
	Name         string      `json:"name"`
}

// WebAuthn credentials (A.4). The full go-webauthn Credential is stored as JSON.
func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.Credential,
		arg.Name,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Credential,
	)
	return i, err
}

const listAddressbookObjects = `-- name: ListAddressbookObjects :many
SELECT id, addressbook_id, uid, data, etag, parsed, created_at, updated_at FROM addressbook_objects WHERE addressbook_id = $1 ORDER BY uid
`

func (q *Queries) ListAddressbookObjects(ctx context.Context, addressbookID pgtype.UUID) ([]AddressbookObject, error) {
	rows, err := q.db.Query(ctx, listAddressbookObjects, addressbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressbookObject{}
	for rows.Next() {
		var i AddressbookObject
		if err := rows.Scan(
			&i.ID,
			&i.AddressbookID,
			&i.Uid,
			&i.Data,
			&i.Etag,
			&i.Parsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddressbooks = `-- name: ListAddressbooks :many
SELECT id, user_id, uri, name, ctag, created_at FROM addressbooks WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAddressbooks(ctx context.Context, userID pgtype.UUID) ([]Addressbook, error) {
	rows, err := q.db.Query(ctx, listAddressbooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Addressbook{}
	for rows.Next() {
		var i Addressbook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uri,
			&i.Name,
			&i.Ctag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, user_id, event, ip, user_agent, detail, created_at FROM audit_log WHERE user_id = $1 ORDER BY id DESC LIMIT $2
`

type ListAuditLogParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Event,
			&i.Ip,
			&i.UserAgent,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarObjects = `-- name: ListCalendarObjects :many
SELECT id, calendar_id, uid, data, etag, parsed, created_at, updated_at FROM calendar_objects WHERE calendar_id = $1 ORDER BY uid
`

func (q *Queries) ListCalendarObjects(ctx context.Context, calendarID pgtype.UUID) ([]CalendarObject, error) {
	rows, err := q.db.Query(ctx, listCalendarObjects, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarObject{}
	for rows.Next() {
		var i CalendarObject
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.Data,
			&i.Etag,
			&i.Parsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, user_id, uri, name, color, ctag, created_at, components FROM calendars WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListCalendars(ctx context.Context, userID pgtype.UUID) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listCalendars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calendar{}
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uri,
			&i.Name,
			&i.Color,
			&i.Ctag,
			&i.CreatedAt,
			&i.Components,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesSince = `-- name: ListChangesSince :many
SELECT cl.seq, cl.op, cl.version, cl.created_at,
       n.id AS node_id, n.name, n.parent_id, n.is_dir, n.size, n.content_hash, n.disk_path,
       (n.deleted_at IS NOT NULL)::bool AS deleted
FROM change_log cl
JOIN nodes n ON n.id = cl.node_id
WHERE cl.user_id = $1 AND cl.seq > $2
ORDER BY cl.seq
LIMIT $3
`

type ListChangesSinceParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Seq    int64       `json:"seq"`
	Lim    int32       `json:"lim"`
}

type ListChangesSinceRow struct {
	Seq         int64              `json:"seq"`
	Op          string             `json:"op"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	NodeID      pgtype.UUID        `json:"node_id"`
	Name        string             `json:"name"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsDir       bool               `json:"is_dir"`
	Size        pgtype.Int8        `json:"size"`
	ContentHash pgtype.Text        `json:"content_hash"`
	DiskPath    pgtype.Text        `json:"disk_path"`
	Deleted     bool               `json:"deleted"`
}

// Delta sync: changes after seq, with the node's current state.
// LIMIT — pagination: large deltas aren't returned in a single chunk (3.1).
// content_hash — lets the client tell a real change from a touch.
func (q *Queries) ListChangesSince(ctx context.Context, arg ListChangesSinceParams) ([]ListChangesSinceRow, error) {
	rows, err := q.db.Query(ctx, listChangesSince, arg.UserID, arg.Seq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangesSinceRow{}
	for rows.Next() {
		var i ListChangesSinceRow
		if err := rows.Scan(
			&i.Seq,
			&i.Op,
			&i.Version,
			&i.CreatedAt,
			&i.NodeID,
			&i.Name,
			&i.ParentID,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesSinceUnderPrefix = `-- name: ListChangesSinceUnderPrefix :many
SELECT cl.seq, cl.op, cl.version, cl.created_at,
       n.id AS node_id, n.name, n.parent_id, n.is_dir, n.size, n.content_hash, n.disk_path,
       (n.deleted_at IS NOT NULL)::bool AS deleted
FROM change_log cl
JOIN nodes n ON n.id = cl.node_id
WHERE cl.user_id = $1 AND cl.seq > $2 AND n.disk_path LIKE $3::text ESCAPE '\'
ORDER BY cl.seq
LIMIT $4
`

type ListChangesSinceUnderPrefixParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Seq    int64       `json:"seq"`
	Prefix string      `json:"prefix"`
	Lim    int32       `json:"lim"`
}

type ListChangesSinceUnderPrefixRow struct {
	Seq         int64              `json:"seq"`
	Op          string             `json:"op"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	NodeID      pgtype.UUID        `json:"node_id"`
	Name        string             `json:"name"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsDir       bool               `json:"is_dir"`
	Size        pgtype.Int8        `json:"size"`
	ContentHash pgtype.Text        `json:"content_hash"`
	DiskPath    pgtype.Text        `json:"disk_path"`
	Deleted     bool               `json:"deleted"`
}

func (q *Queries) ListChangesSinceUnderPrefix(ctx context.Context, arg ListChangesSinceUnderPrefixParams) ([]ListChangesSinceUnderPrefixRow, error) {
	rows, err := q.db.Query(ctx, listChangesSinceUnderPrefix,
		arg.UserID,
		arg.Seq,
		arg.Prefix,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangesSinceUnderPrefixRow{}
	for rows.Next() {
		var i ListChangesSinceUnderPrefixRow
		if err := rows.Scan(
			&i.Seq,
			&i.Op,
			&i.Version,
			&i.CreatedAt,
			&i.NodeID,
			&i.Name,
			&i.ParentID,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes
WHERE user_id = $1 AND parent_id = $2 AND deleted_at IS NULL
ORDER BY is_dir DESC, name
`

type ListChildrenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listChildren, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Mime,
			&i.IsVault,
			&i.Version,
			&i.ModifiedAt,
			&i.ModifiedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.IsConflictLoser,
			&i.ConflictOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT id, user_id, name, kind, last_seen_at, created_at, secret_hash, token_hash FROM devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.SecretHash,
			&i.TokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTombstones = `-- name: ListExpiredTombstones :many
SELECT id, user_id, disk_path, is_dir FROM nodes
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

type ListExpiredTombstonesRow struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	DiskPath pgtype.Text `json:"disk_path"`
	IsDir    bool        `json:"is_dir"`
}

func (q *Queries) ListExpiredTombstones(ctx context.Context, deletedAt pgtype.Timestamptz) ([]ListExpiredTombstonesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTombstones, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredTombstonesRow{}
	for rows.Next() {
		var i ListExpiredTombstonesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DiskPath,
			&i.IsDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileVersions = `-- name: ListFileVersions :many
SELECT id, node_id, version, content_hash, disk_path, size, device_id, is_conflict_loser, created_at FROM file_versions WHERE node_id = $1 ORDER BY version DESC
`

func (q *Queries) ListFileVersions(ctx context.Context, nodeID pgtype.UUID) ([]FileVersion, error) {
	rows, err := q.db.Query(ctx, listFileVersions, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileVersion{}
	for rows.Next() {
		var i FileVersion
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Version,
			&i.ContentHash,
			&i.DiskPath,
			&i.Size,
			&i.DeviceID,
			&i.IsConflictLoser,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodes = `-- name: ListLiveNodes :many
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListLiveNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listLiveNodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Mime,
			&i.IsVault,
			&i.Version,
			&i.ModifiedAt,
			&i.ModifiedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.IsConflictLoser,
			&i.ConflictOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeChildren = `-- name: ListNodeChildren :many
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY is_dir DESC, name
`

// Children of a node without owner scoping (for listing a shared folder after canAccess).
func (q *Queries) ListNodeChildren(ctx context.Context, parentID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodeChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Mime,
			&i.IsVault,
			&i.Version,
			&i.ModifiedAt,
			&i.ModifiedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.IsConflictLoser,
			&i.ConflictOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesWithExcessVersions = `-- name: ListNodesWithExcessVersions :many
SELECT node_id FROM file_versions GROUP BY node_id HAVING count(*) > $1
`

// Nodes that have more than keep versions (trimming candidates).
func (q *Queries) ListNodesWithExcessVersions(ctx context.Context, keep interface{}) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNodesWithExcessVersions, keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var node_id pgtype.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPrefs = `-- name: ListNotificationPrefs :many
SELECT event_key, channel, enabled FROM notification_prefs WHERE user_id = $1
`

type ListNotificationPrefsRow struct {
	EventKey string `json:"event_key"`
	Channel  string `json:"channel"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) ListNotificationPrefs(ctx context.Context, userID pgtype.UUID) ([]ListNotificationPrefsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationPrefs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationPrefsRow{}
	for rows.Next() {
		var i ListNotificationPrefsRow
		if err := rows.Scan(&i.EventKey, &i.Channel, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSettings = `-- name: ListPublicSettings :many
SELECT key, value, is_secret, updated_at, updated_by FROM settings WHERE is_secret = false ORDER BY key
`

func (q *Queries) ListPublicSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listPublicSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaCandidates = `-- name: ListQuotaCandidates :many
SELECT id, email, storage_used, storage_quota FROM users
WHERE storage_quota IS NOT NULL
  AND storage_used * 10 >= storage_quota * 9
  AND quota_notified_at IS NULL
`

type ListQuotaCandidatesRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	StorageUsed  int64       `json:"storage_used"`
	StorageQuota pgtype.Int8 `json:"storage_quota"`
}

func (q *Queries) ListQuotaCandidates(ctx context.Context) ([]ListQuotaCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listQuotaCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotaCandidatesRow{}
	for rows.Next() {
		var i ListQuotaCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StorageUsed,
			&i.StorageQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootNodes = `-- name: ListRootNodes :many
SELECT id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of FROM nodes
WHERE user_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
ORDER BY is_dir DESC, name
`

func (q *Queries) ListRootNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listRootNodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Mime,
			&i.IsVault,
			&i.Version,
			&i.ModifiedAt,
			&i.ModifiedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.IsConflictLoser,
			&i.ConflictOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretKeys = `-- name: ListSecretKeys :many
SELECT key FROM settings WHERE is_secret = true ORDER BY key
`

func (q *Queries) ListSecretKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSecretKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForResource = `-- name: ListSharesForResource :many
SELECT id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash FROM resource_shares WHERE resource_type = $1 AND resource_id = $2
`

type ListSharesForResourceParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

func (q *Queries) ListSharesForResource(ctx context.Context, arg ListSharesForResourceParams) ([]ResourceShare, error) {
	rows, err := q.db.Query(ctx, listSharesForResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceShare{}
	for rows.Next() {
		var i ResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.OwnerID,
			&i.SharedWithUser,
			&i.ShareLinkToken,
			&i.Access,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SharePasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForUser = `-- name: ListSharesForUser :many
SELECT id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash FROM resource_shares
WHERE shared_with_user = $1 AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

func (q *Queries) ListSharesForUser(ctx context.Context, sharedWithUser pgtype.UUID) ([]ResourceShare, error) {
	rows, err := q.db.Query(ctx, listSharesForUser, sharedWithUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceShare{}
	for rows.Next() {
		var i ResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.OwnerID,
			&i.SharedWithUser,
			&i.ShareLinkToken,
			&i.Access,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SharePasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstonedNodePaths = `-- name: ListTombstonedNodePaths :many
SELECT disk_path FROM nodes
WHERE user_id = $1 AND deleted_at IS NOT NULL AND disk_path IS NOT NULL
`

// Paths of trashed (soft-deleted) nodes — so a rescan doesn't re-import their files.
func (q *Queries) ListTombstonedNodePaths(ctx context.Context, userID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listTombstonedNodePaths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var disk_path pgtype.Text
		if err := rows.Scan(&disk_path); err != nil {
			return nil, err
		}
		items = append(items, disk_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashNodes = `-- name: ListTrashNodes :many
SELECT n.id, n.user_id, n.parent_id, n.name, n.is_dir, n.size, n.content_hash, n.disk_path, n.mime, n.is_vault, n.version, n.modified_at, n.modified_by, n.deleted_at, n.created_at, n.is_conflict_loser, n.conflict_of FROM nodes n
WHERE n.user_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.user_id = n.user_id AND p.deleted_at IS NULL))
ORDER BY n.deleted_at DESC
`

func (q *Queries) ListTrashNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listTrashNodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.ContentHash,
			&i.DiskPath,
			&i.Mime,
			&i.IsVault,
			&i.Version,
			&i.ModifiedAt,
			&i.ModifiedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.IsConflictLoser,
			&i.ConflictOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedSubtree = `-- name: ListTrashedSubtree :many
SELECT id, disk_path, is_dir FROM nodes
WHERE user_id = $1
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
  AND deleted_at IS NOT NULL
`

type ListTrashedSubtreeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Prefix string      `json:"prefix"`
}

type ListTrashedSubtreeRow struct {
	ID       pgtype.UUID `json:"id"`
	DiskPath pgtype.Text `json:"disk_path"`
	IsDir    bool        `json:"is_dir"`
}

func (q *Queries) ListTrashedSubtree(ctx context.Context, arg ListTrashedSubtreeParams) ([]ListTrashedSubtreeRow, error) {
	rows, err := q.db.Query(ctx, listTrashedSubtree, arg.UserID, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedSubtreeRow{}
	for rows.Next() {
		var i ListTrashedSubtreeRow
		if err := rows.Scan(&i.ID, &i.DiskPath, &i.IsDir); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM backup_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, userID pgtype.UUID) ([]BackupCode, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupCode{}
	for rows.Next() {
		var i BackupCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithUsage = `-- name: ListUsersWithUsage :many
SELECT u.id, u.email, u.role, u.storage_quota, u.created_at,
       COALESCE((
           SELECT SUM(n.size) FROM nodes n
           WHERE n.user_id = u.id AND n.deleted_at IS NULL AND n.is_dir = false
       ), 0)::bigint AS used
FROM users u
ORDER BY u.created_at
`

type ListUsersWithUsageRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	StorageQuota pgtype.Int8        `json:"storage_quota"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Used         int64              `json:"used"`
}

// Users with used space (sum of live file sizes) — for the admin dashboard.
func (q *Queries) ListUsersWithUsage(ctx context.Context) ([]ListUsersWithUsageRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithUsageRow{}
	for rows.Next() {
		var i ListUsersWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.StorageQuota,
			&i.CreatedAt,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT id, user_id, credential_id, name, created_at, last_used_at, credential FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Credential,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebdavDevicesByEmail = `-- name: ListWebdavDevicesByEmail :many
SELECT d.id, d.user_id, d.name, d.kind, d.last_seen_at, d.created_at, d.secret_hash, d.token_hash FROM devices d
JOIN users u ON u.id = d.user_id
WHERE u.email = $1 AND d.kind = 'webdav' AND d.secret_hash IS NOT NULL
`

func (q *Queries) ListWebdavDevicesByEmail(ctx context.Context, email string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listWebdavDevicesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.SecretHash,
			&i.TokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE backup_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}

const markQuotaNotified = `-- name: MarkQuotaNotified :exec
UPDATE users SET quota_notified_at = now() WHERE id = $1
`

func (q *Queries) MarkQuotaNotified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markQuotaNotified, id)
	return err
}

const nextChangeSeq = `-- name: NextChangeSeq :one
UPDATE users SET change_seq = change_seq + 1 WHERE id = $1 RETURNING change_seq
`

func (q *Queries) NextChangeSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextChangeSeq, id)
	var change_seq int64
	err := row.Scan(&change_seq)
	return change_seq, err
}

const notificationPrefsForEvent = `-- name: NotificationPrefsForEvent :many
SELECT channel, enabled FROM notification_prefs WHERE user_id = $1 AND event_key = $2
`

type NotificationPrefsForEventParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	EventKey string      `json:"event_key"`
}

type NotificationPrefsForEventRow struct {
	Channel string `json:"channel"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) NotificationPrefsForEvent(ctx context.Context, arg NotificationPrefsForEventParams) ([]NotificationPrefsForEventRow, error) {
	rows, err := q.db.Query(ctx, notificationPrefsForEvent, arg.UserID, arg.EventKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPrefsForEventRow{}
	for rows.Next() {
		var i NotificationPrefsForEventRow
		if err := rows.Scan(&i.Channel, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :exec
UPDATE webauthn_credentials SET name = $3 WHERE id = $1 AND user_id = $2
`

type RenameWebAuthnCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, renameWebAuthnCredential, arg.ID, arg.UserID, arg.Name)
	return err
}

const rewriteSubtreePaths = `-- name: RewriteSubtreePaths :exec
UPDATE nodes
SET disk_path = $1::text || substring(disk_path FROM char_length($2::text) + 1)
WHERE user_id = $3
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
`

type RewriteSubtreePathsParams struct {
	NewPrefix string      `json:"new_prefix"`
	OldPrefix string      `json:"old_prefix"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Rewrite disk_path of a node and its whole subtree on rename/move (mirrors the tree).
func (q *Queries) RewriteSubtreePaths(ctx context.Context, arg RewriteSubtreePathsParams) error {
	_, err := q.db.Exec(ctx, rewriteSubtreePaths, arg.NewPrefix, arg.OldPrefix, arg.UserID)
	return err
}

const rewriteTombstonedSubtreePaths = `-- name: RewriteTombstonedSubtreePaths :exec
UPDATE nodes
SET disk_path = $1::text || substring(disk_path FROM char_length($2::text) + 1)
WHERE user_id = $3
  AND deleted_at IS NOT NULL
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
`

type RewriteTombstonedSubtreePathsParams struct {
	NewPrefix string      `json:"new_prefix"`
	OldPrefix string      `json:"old_prefix"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Like RewriteSubtreePaths, but only for trashed nodes — so restoring doesn't
// touch a LIVE node sharing the same disk_path (the name was reused after deletion).
func (q *Queries) RewriteTombstonedSubtreePaths(ctx context.Context, arg RewriteTombstonedSubtreePathsParams) error {
	_, err := q.db.Exec(ctx, rewriteTombstonedSubtreePaths, arg.NewPrefix, arg.OldPrefix, arg.UserID)
	return err
}

const setAddressbookName = `-- name: SetAddressbookName :exec
UPDATE addressbooks SET name = $2 WHERE id = $1 AND user_id = $3
`

type SetAddressbookNameParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetAddressbookName(ctx context.Context, arg SetAddressbookNameParams) error {
	_, err := q.db.Exec(ctx, setAddressbookName, arg.ID, arg.Name, arg.UserID)
	return err
}

const setCalendarColor = `-- name: SetCalendarColor :exec
UPDATE calendars SET color = $2 WHERE id = $1 AND user_id = $3
`

type SetCalendarColorParams struct {
	ID     pgtype.UUID `json:"id"`
	Color  string      `json:"color"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetCalendarColor(ctx context.Context, arg SetCalendarColorParams) error {
	_, err := q.db.Exec(ctx, setCalendarColor, arg.ID, arg.Color, arg.UserID)
	return err
}

const setCalendarName = `-- name: SetCalendarName :exec
UPDATE calendars SET name = $2 WHERE id = $1 AND user_id = $3
`

type SetCalendarNameParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetCalendarName(ctx context.Context, arg SetCalendarNameParams) error {
	_, err := q.db.Exec(ctx, setCalendarName, arg.ID, arg.Name, arg.UserID)
	return err
}

const setDeviceTokenHash = `-- name: SetDeviceTokenHash :exec
UPDATE devices SET token_hash = $2 WHERE id = $1
`

type SetDeviceTokenHashParams struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash pgtype.Text `json:"token_hash"`
}

func (q *Queries) SetDeviceTokenHash(ctx context.Context, arg SetDeviceTokenHashParams) error {
	_, err := q.db.Exec(ctx, setDeviceTokenHash, arg.ID, arg.TokenHash)
	return err
}

const setSharePasswordHash = `-- name: SetSharePasswordHash :exec
UPDATE resource_shares SET share_password_hash = $2 WHERE id = $1
`

type SetSharePasswordHashParams struct {
	ID                pgtype.UUID `json:"id"`
	SharePasswordHash pgtype.Text `json:"share_password_hash"`
}

func (q *Queries) SetSharePasswordHash(ctx context.Context, arg SetSharePasswordHashParams) error {
	_, err := q.db.Exec(ctx, setSharePasswordHash, arg.ID, arg.SharePasswordHash)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
UPDATE users SET language = $2 WHERE id = $1
`

type SetUserLanguageParams struct {
	ID       pgtype.UUID `json:"id"`
	Language string      `json:"language"`
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.Exec(ctx, setUserLanguage, arg.ID, arg.Language)
	return err
}

const sharedAccessForUser = `-- name: SharedAccessForUser :one
WITH RECURSIVE chain(node_id, parent_id) AS (
    SELECT n.id, n.parent_id FROM nodes n WHERE n.id = $2
    UNION ALL
    SELECT n.id, n.parent_id FROM nodes n JOIN chain c ON n.id = c.parent_id
)
SELECT
    COALESCE(bool_or(rs.access = 'read_write'), false)::bool AS can_write,
    (count(rs.id) > 0)::bool AS can_read
FROM resource_shares rs
JOIN chain c ON rs.resource_id = c.node_id
WHERE rs.resource_type = 'file_node'
  AND rs.shared_with_user = $1
  AND (rs.expires_at IS NULL OR rs.expires_at > now())
`

type SharedAccessForUserParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	StartID pgtype.UUID `json:"start_id"`
}

type SharedAccessForUserRow struct {
	CanWrite bool `json:"can_write"`
	CanRead  bool `json:"can_read"`
}

func (q *Queries) SharedAccessForUser(ctx context.Context, arg SharedAccessForUserParams) (SharedAccessForUserRow, error) {
	row := q.db.QueryRow(ctx, sharedAccessForUser, arg.UserID, arg.StartID)
	var i SharedAccessForUserRow
	err := row.Scan(&i.CanWrite, &i.CanRead)
	return i, err
}

const softDeleteNode = `-- name: SoftDeleteNode :exec
UPDATE nodes SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteNode, id)
	return err
}

const softDeleteSubtree = `-- name: SoftDeleteSubtree :exec
UPDATE nodes
SET deleted_at = now()
WHERE user_id = $1
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
  AND deleted_at IS NULL
`

type SoftDeleteSubtreeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Prefix string      `json:"prefix"`
}

// Soft-delete a node and its whole subtree (disk is cleaned up by GC, step 0.6).
func (q *Queries) SoftDeleteSubtree(ctx context.Context, arg SoftDeleteSubtreeParams) error {
	_, err := q.db.Exec(ctx, softDeleteSubtree, arg.UserID, arg.Prefix)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const trimNodeVersions = `-- name: TrimNodeVersions :many
DELETE FROM file_versions
WHERE id IN (
    SELECT fv.id FROM file_versions fv
    WHERE fv.node_id = $1
    ORDER BY fv.version DESC OFFSET $2
)
RETURNING disk_path
`

type TrimNodeVersionsParams struct {
	Nid  pgtype.UUID `json:"nid"`
	Keep int32       `json:"keep"`
}

// Delete versions beyond the keep newest; return snapshot paths for disk cleanup.
func (q *Queries) TrimNodeVersions(ctx context.Context, arg TrimNodeVersionsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, trimNodeVersions, arg.Nid, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var disk_path pgtype.Text
		if err := rows.Scan(&disk_path); err != nil {
			return nil, err
		}
		items = append(items, disk_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeleteSubtree = `-- name: UndeleteSubtree :exec
UPDATE nodes SET deleted_at = NULL
WHERE user_id = $1
  AND (disk_path = $2::text OR disk_path LIKE $2::text || '/%')
  AND deleted_at IS NOT NULL
`

type UndeleteSubtreeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Prefix string      `json:"prefix"`
}

func (q *Queries) UndeleteSubtree(ctx context.Context, arg UndeleteSubtreeParams) error {
	_, err := q.db.Exec(ctx, undeleteSubtree, arg.UserID, arg.Prefix)
	return err
}

const updateNodeContent = `-- name: UpdateNodeContent :one
UPDATE nodes
SET size = $2, content_hash = $3, mime = $4, version = version + 1, modified_at = now(), modified_by = $5
WHERE id = $1
RETURNING id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of
`

type UpdateNodeContentParams struct {
	ID          pgtype.UUID `json:"id"`
	Size        pgtype.Int8 `json:"size"`
	ContentHash pgtype.Text `json:"content_hash"`
	Mime        pgtype.Text `json:"mime"`
	ModifiedBy  pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateNodeContent(ctx context.Context, arg UpdateNodeContentParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeContent,
		arg.ID,
		arg.Size,
		arg.ContentHash,
		arg.Mime,
		arg.ModifiedBy,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const updateNodeName = `-- name: UpdateNodeName :one
UPDATE nodes
SET name = $2, version = version + 1, modified_at = now(), modified_by = $3
WHERE id = $1
RETURNING id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of
`

type UpdateNodeNameParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateNodeName(ctx context.Context, arg UpdateNodeNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeName, arg.ID, arg.Name, arg.ModifiedBy)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const updateNodeParent = `-- name: UpdateNodeParent :one
UPDATE nodes
SET parent_id = $2, version = version + 1, modified_at = now(), modified_by = $3
WHERE id = $1
RETURNING id, user_id, parent_id, name, is_dir, size, content_hash, disk_path, mime, is_vault, version, modified_at, modified_by, deleted_at, created_at, is_conflict_loser, conflict_of
`

type UpdateNodeParentParams struct {
	ID         pgtype.UUID `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateNodeParent(ctx context.Context, arg UpdateNodeParentParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeParent, arg.ID, arg.ParentID, arg.ModifiedBy)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.IsDir,
		&i.Size,
		&i.ContentHash,
		&i.DiskPath,
		&i.Mime,
		&i.IsVault,
		&i.Version,
		&i.ModifiedAt,
		&i.ModifiedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.IsConflictLoser,
		&i.ConflictOf,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users SET password_hash = $2, token_version = token_version + 1, must_change_password = false
WHERE id = $1 RETURNING id, tenant_id, email, password_hash, storage_quota, storage_used, created_at, role, change_seq, quota_notified_at, token_version, language, must_change_password
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

// Password change: new hash + bump token_version (invalidates all active sessions)
// + clear the forced-change flag (A.2).
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.Role,
		&i.ChangeSeq,
		&i.QuotaNotifiedAt,
		&i.TokenVersion,
		&i.Language,
		&i.MustChangePassword,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET storage_quota = $2, role = $3 WHERE id = $1 RETURNING id, tenant_id, email, password_hash, storage_quota, storage_used, created_at, role, change_seq, quota_notified_at, token_version, language, must_change_password
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	StorageQuota pgtype.Int8 `json:"storage_quota"`
	Role         string      `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.StorageQuota, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.Role,
		&i.ChangeSeq,
		&i.QuotaNotifiedAt,
		&i.TokenVersion,
		&i.Language,
		&i.MustChangePassword,
	)
	return i, err
}

const updateWebAuthnCredential = `-- name: UpdateWebAuthnCredential :exec
UPDATE webauthn_credentials SET credential = $2, last_used_at = now() WHERE credential_id = $1
`

type UpdateWebAuthnCredentialParams struct {
	CredentialID []byte `json:"credential_id"`
	Credential   []byte `json:"credential"`
}

// A.5: persist the credential after a login (sign_count bumps; clone detection) + last used.
func (q *Queries) UpdateWebAuthnCredential(ctx context.Context, arg UpdateWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredential, arg.CredentialID, arg.Credential)
	return err
}

const upsertAddressbookObject = `-- name: UpsertAddressbookObject :one
INSERT INTO addressbook_objects (addressbook_id, uid, data, etag, parsed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (addressbook_id, uid) DO UPDATE
SET data = EXCLUDED.data, etag = EXCLUDED.etag, parsed = EXCLUDED.parsed, updated_at = now()
RETURNING id, addressbook_id, uid, data, etag, parsed, created_at, updated_at
`

type UpsertAddressbookObjectParams struct {
	AddressbookID pgtype.UUID `json:"addressbook_id"`
	Uid           string      `json:"uid"`
	Data          string      `json:"data"`
	Etag          string      `json:"etag"`
	Parsed        []byte      `json:"parsed"`
}

// == addressbook_objects ==
func (q *Queries) UpsertAddressbookObject(ctx context.Context, arg UpsertAddressbookObjectParams) (AddressbookObject, error) {
	row := q.db.QueryRow(ctx, upsertAddressbookObject,
		arg.AddressbookID,
		arg.Uid,
		arg.Data,
		arg.Etag,
		arg.Parsed,
	)
	var i AddressbookObject
	err := row.Scan(
		&i.ID,
		&i.AddressbookID,
		&i.Uid,
		&i.Data,
		&i.Etag,
		&i.Parsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCalendarObject = `-- name: UpsertCalendarObject :one
INSERT INTO calendar_objects (calendar_id, uid, data, etag, parsed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (calendar_id, uid) DO UPDATE
SET data = EXCLUDED.data, etag = EXCLUDED.etag, parsed = EXCLUDED.parsed, updated_at = now()
RETURNING id, calendar_id, uid, data, etag, parsed, created_at, updated_at
`

type UpsertCalendarObjectParams struct {
	CalendarID pgtype.UUID `json:"calendar_id"`
	Uid        string      `json:"uid"`
	Data       string      `json:"data"`
	Etag       string      `json:"etag"`
	Parsed     []byte      `json:"parsed"`
}

// == calendar_objects ==
func (q *Queries) UpsertCalendarObject(ctx context.Context, arg UpsertCalendarObjectParams) (CalendarObject, error) {
	row := q.db.QueryRow(ctx, upsertCalendarObject,
		arg.CalendarID,
		arg.Uid,
		arg.Data,
		arg.Etag,
		arg.Parsed,
	)
	var i CalendarObject
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.Data,
		&i.Etag,
		&i.Parsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnownLogin = `-- name: UpsertKnownLogin :one
INSERT INTO known_logins (user_id, fingerprint, user_agent, ip)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, fingerprint) DO UPDATE SET last_seen = now(), ip = EXCLUDED.ip
RETURNING (xmax = 0)::bool AS inserted
`

type UpsertKnownLoginParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Fingerprint string      `json:"fingerprint"`
	UserAgent   string      `json:"user_agent"`
	Ip          string      `json:"ip"`
}

func (q *Queries) UpsertKnownLogin(ctx context.Context, arg UpsertKnownLoginParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertKnownLogin,
		arg.UserID,
		arg.Fingerprint,
		arg.UserAgent,
		arg.Ip,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const upsertNotificationPref = `-- name: UpsertNotificationPref :exec
INSERT INTO notification_prefs (user_id, event_key, channel, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, event_key, channel) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertNotificationPrefParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	EventKey string      `json:"event_key"`
	Channel  string      `json:"channel"`
	Enabled  bool        `json:"enabled"`
}

func (q *Queries) UpsertNotificationPref(ctx context.Context, arg UpsertNotificationPrefParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPref,
		arg.UserID,
		arg.EventKey,
		arg.Channel,
		arg.Enabled,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, is_secret, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    is_secret = EXCLUDED.is_secret,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertSettingParams struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	IsSecret  bool        `json:"is_secret"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	return err
}

const upsertUserTOTP = `-- name: UpsertUserTOTP :exec

INSERT INTO user_totp (user_id, secret, enabled, confirmed_at)
VALUES ($1, $2, false, NULL)
ON CONFLICT (user_id) DO UPDATE SET secret = EXCLUDED.secret, enabled = false, confirmed_at = NULL, created_at = now()
`

type UpsertUserTOTPParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Secret string      `json:"secret"`
}

// TOTP 2FA (A.3). Secret is AES-GCM ciphertext.
// Begin (or restart) TOTP setup: store an encrypted secret, not yet confirmed.
func (q *Queries) UpsertUserTOTP(ctx context.Context, arg UpsertUserTOTPParams) error {
	_, err := q.db.Exec(ctx, upsertUserTOTP, arg.UserID, arg.Secret)
	return err
}
