// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Returns a single album if it contains at least one accessible song for the user.
	AccessibleAlbum(ctx context.Context, arg AccessibleAlbumParams) (Album, error)
	// Returns accessible albums ordered by name ascending (alphabeticalByName).
	AccessibleAlbumListAlpha(ctx context.Context, arg AccessibleAlbumListAlphaParams) ([]AccessibleAlbumListAlphaRow, error)
	// Returns accessible albums for a specific genre.
	AccessibleAlbumListByGenre(ctx context.Context, arg AccessibleAlbumListByGenreParams) ([]AccessibleAlbumListByGenreRow, error)
	// Returns accessible albums for a year range, ordered by year ascending.
	AccessibleAlbumListByYearAsc(ctx context.Context, arg AccessibleAlbumListByYearAscParams) ([]AccessibleAlbumListByYearAscRow, error)
	// Returns accessible albums for a year range, ordered by year descending.
	AccessibleAlbumListByYearDesc(ctx context.Context, arg AccessibleAlbumListByYearDescParams) ([]AccessibleAlbumListByYearDescRow, error)
	// Returns accessible albums ordered by total play count (from play_history).
	AccessibleAlbumListFrequent(ctx context.Context, arg AccessibleAlbumListFrequentParams) ([]AccessibleAlbumListFrequentRow, error)
	// Returns accessible albums ordered by creation date descending (newest first).
	AccessibleAlbumListNewest(ctx context.Context, arg AccessibleAlbumListNewestParams) ([]AccessibleAlbumListNewestRow, error)
	// Returns accessible albums in random order.
	// DISTINCT must be applied before the random ordering: Postgres rejects
	// "SELECT DISTINCT ... ORDER BY random()" because random() is not in the select
	// list. Dedupe in a derived table, then order the distinct rows randomly.
	AccessibleAlbumListRandom(ctx context.Context, arg AccessibleAlbumListRandomParams) ([]AccessibleAlbumListRandomRow, error)
	// Returns accessible albums ordered by most recent play (from play_history).
	AccessibleAlbumListRecent(ctx context.Context, arg AccessibleAlbumListRecentParams) ([]AccessibleAlbumListRecentRow, error)
	// Returns albums for a given artist that contain at least one accessible song.
	AccessibleAlbumsByArtist(ctx context.Context, arg AccessibleAlbumsByArtistParams) ([]Album, error)
	// Returns a single artist if the user has at least one accessible song by that artist.
	AccessibleArtist(ctx context.Context, arg AccessibleArtistParams) (Artist, error)
	// Returns all artists that have at least one accessible song for the user.
	AccessibleArtists(ctx context.Context, userID pgtype.UUID) ([]Artist, error)
	// Returns distinct authors with their sort_name for navigation, from accessible books.
	// Both name and sort_name are selected so ORDER BY sort_name satisfies DISTINCT rules.
	AccessibleAuthors(ctx context.Context, userID pgtype.UUID) ([]AccessibleAuthorsRow, error)
	// Returns a single book by id if it is accessible to the user (own or shared).
	AccessibleBook(ctx context.Context, arg AccessibleBookParams) (Book, error)
	// Returns distinct genre/tag values from accessible books, ordered alphabetically.
	AccessibleBookGenres(ctx context.Context, userID pgtype.UUID) ([]string, error)
	// Returns all books accessible to a user, ordered by sort_title, with pagination.
	AccessibleBooksAll(ctx context.Context, arg AccessibleBooksAllParams) ([]Book, error)
	// Returns books accessible to a user filtered by author name.
	AccessibleBooksByAuthor(ctx context.Context, arg AccessibleBooksByAuthorParams) ([]Book, error)
	// Returns books accessible to a user filtered by genre/tag.
	AccessibleBooksByGenre(ctx context.Context, arg AccessibleBooksByGenreParams) ([]Book, error)
	// Returns books accessible to a user for a given series, ordered by series_index.
	AccessibleBooksBySeries(ctx context.Context, arg AccessibleBooksBySeriesParams) ([]Book, error)
	// Returns recently added books accessible to a user, newest first.
	AccessibleBooksNewest(ctx context.Context, arg AccessibleBooksNewestParams) ([]Book, error)
	// Returns distinct non-empty genres from accessible songs/albums with counts.
	AccessibleGenres(ctx context.Context, userID pgtype.UUID) ([]AccessibleGenresRow, error)
	// Returns distinct series names from accessible books, ordered alphabetically.
	AccessibleSeries(ctx context.Context, userID pgtype.UUID) ([]pgtype.Text, error)
	// Returns a single song by id if it is accessible to the user.
	AccessibleSong(ctx context.Context, arg AccessibleSongParams) (Song, error)
	// Returns one accessible song matching the given title (case-insensitive),
	// for the legacy getLyrics endpoint which is keyed by artist+title.
	AccessibleSongByTitle(ctx context.Context, arg AccessibleSongByTitleParams) (Song, error)
	// Returns all songs accessible to a user: own songs plus songs whose file node is
	// inside a folder shared to that user (recursively), excluding expired shares.
	AccessibleSongs(ctx context.Context, userID pgtype.UUID) ([]Song, error)
	// Returns accessible songs for a given album, ordered by disc then track.
	AccessibleSongsByAlbum(ctx context.Context, arg AccessibleSongsByAlbumParams) ([]Song, error)
	// Returns accessible songs for a given artist ordered by title, with album/artist names.
	AccessibleSongsByArtist(ctx context.Context, arg AccessibleSongsByArtistParams) ([]AccessibleSongsByArtistRow, error)
	AddPlayQueueEntry(ctx context.Context, arg AddPlayQueueEntryParams) error
	AddPlaylistSong(ctx context.Context, arg AddPlaylistSongParams) error
	AddressbookShareForUser(ctx context.Context, arg AddressbookShareForUserParams) (pgtype.UUID, error)
	AppendChange(ctx context.Context, arg AppendChangeParams) (ChangeLog, error)
	ApprovePairing(ctx context.Context, arg ApprovePairingParams) (pgtype.UUID, error)
	// Which interactive second factors the user has. Used by Login to branch.
	AvailableMFAFactors(ctx context.Context, userID pgtype.UUID) (AvailableMFAFactorsRow, error)
	BookAuthors(ctx context.Context, bookID pgtype.UUID) ([]BookAuthorsRow, error)
	BookTags(ctx context.Context, bookID pgtype.UUID) ([]string, error)
	BumpAddressbookCtag(ctx context.Context, id pgtype.UUID) error
	BumpCalendarCtag(ctx context.Context, id pgtype.UUID) error
	BumpNodeVersion(ctx context.Context, id pgtype.UUID) (int64, error)
	// A user's access level to a file_node, accounting for inheritance: we check
	// the node itself AND all its ancestors (recursive CTE), taking active shares for the user.
	CalendarShareForUser(ctx context.Context, arg CalendarShareForUserParams) (pgtype.UUID, error)
	ClaimEpisodeForDownload(ctx context.Context, arg ClaimEpisodeForDownloadParams) (int64, error)
	ClearBookAuthors(ctx context.Context, bookID pgtype.UUID) error
	ClearBookTags(ctx context.Context, bookID pgtype.UUID) error
	ClearEbookCredentials(ctx context.Context, userID pgtype.UUID) error
	ClearEpisodeDownload(ctx context.Context, arg ClearEpisodeDownloadParams) error
	ClearMusicCredentials(ctx context.Context, userID pgtype.UUID) error
	ClearPlayQueueEntries(ctx context.Context, userID pgtype.UUID) error
	ClearPlaylistSongs(ctx context.Context, playlistID pgtype.UUID) error
	ClearQuotaNotified(ctx context.Context) error
	ConfirmUserTOTP(ctx context.Context, userID pgtype.UUID) error
	// Atomically "claim" an approved pairing: a race between two polls → token exactly once.
	ConsumePairingIfApproved(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Returns the count of accessible albums for a given artist.
	CountAccessibleAlbumsByArtist(ctx context.Context, arg CountAccessibleAlbumsByArtistParams) (int64, error)
	// Returns the total count of books accessible to a user.
	CountAccessibleBooks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountAddressbooks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountCalendars(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountPlaylistSongs(ctx context.Context, playlistID pgtype.UUID) (int64, error)
	CountUserLogins(ctx context.Context, userID pgtype.UUID) (int64, error)
	// == addressbooks ==
	CreateAddressbook(ctx context.Context, arg CreateAddressbookParams) (Addressbook, error)
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error
	// == calendars ==
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	CreateCalendarWithComponents(ctx context.Context, arg CreateCalendarWithComponentsParams) (Calendar, error)
	// A conflict copy is a separate file node.
	CreateConflictNode(ctx context.Context, arg CreateConflictNodeParams) (Node, error)
	CreateDesktopDevice(ctx context.Context, arg CreateDesktopDeviceParams) (Device, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateInternetRadioStation(ctx context.Context, arg CreateInternetRadioStationParams) (InternetRadioStation, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	// Device pairing (device authorization flow, step 3.1.2).
	CreatePairing(ctx context.Context, arg CreatePairingParams) (DevicePairing, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreatePodcastChannel(ctx context.Context, arg CreatePodcastChannelParams) (PodcastChannel, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (ResourceShare, error)
	// Stage 0 base access layer. Queries are extended in steps 0.2–0.5.
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebdavDevice(ctx context.Context, arg CreateWebdavDeviceParams) (Device, error)
	DeleteAddressbook(ctx context.Context, arg DeleteAddressbookParams) error
	DeleteAddressbookObject(ctx context.Context, arg DeleteAddressbookObjectParams) (int64, error)
	DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) error
	DeleteBookByNode(ctx context.Context, nodeID pgtype.UUID) error
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error
	DeleteCalendarObject(ctx context.Context, arg DeleteCalendarObjectParams) (int64, error)
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	DeleteExpiredPairings(ctx context.Context) error
	DeleteInternetRadioStation(ctx context.Context, arg DeleteInternetRadioStationParams) (int64, error)
	DeletePlaylistForUser(ctx context.Context, arg DeletePlaylistForUserParams) error
	DeletePodcastChannelForUser(ctx context.Context, arg DeletePodcastChannelForUserParams) (int64, error)
	DeletePodcastEpisodeForUser(ctx context.Context, arg DeletePodcastEpisodeForUserParams) (int64, error)
	DeleteRating(ctx context.Context, arg DeleteRatingParams) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteShare(ctx context.Context, id pgtype.UUID) error
	DeleteSongByNode(ctx context.Context, nodeID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserTOTP(ctx context.Context, userID pgtype.UUID) error
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	EnabledEbookUsers(ctx context.Context) ([]EnabledEbookUsersRow, error)
	EnabledMusicUsers(ctx context.Context) ([]EnabledMusicUsersRow, error)
	GetActiveShareByToken(ctx context.Context, token string) (ResourceShare, error)
	GetAddressbook(ctx context.Context, id pgtype.UUID) (Addressbook, error)
	GetAddressbookByURI(ctx context.Context, uri string) (Addressbook, error)
	GetAddressbookObject(ctx context.Context, arg GetAddressbookObjectParams) (AddressbookObject, error)
	// Returns album plus artist name in one query for songChild assembly.
	GetAlbumWithArtist(ctx context.Context, id pgtype.UUID) (GetAlbumWithArtistRow, error)
	GetArtistName(ctx context.Context, id pgtype.UUID) (string, error)
	GetBookByNode(ctx context.Context, nodeID pgtype.UUID) (Book, error)
	GetCalendar(ctx context.Context, id pgtype.UUID) (Calendar, error)
	GetCalendarByURI(ctx context.Context, uri string) (Calendar, error)
	GetCalendarObject(ctx context.Context, arg GetCalendarObjectParams) (CalendarObject, error)
	// Device by id (middleware verifies the device token is still live → instant revocation).
	GetDevice(ctx context.Context, id pgtype.UUID) (Device, error)
	GetDeviceByTokenHash(ctx context.Context, tokenHash pgtype.Text) (Device, error)
	GetEbookSettings(ctx context.Context, userID pgtype.UUID) (EbookSetting, error)
	GetEbookSettingsByApiKey(ctx context.Context, apiKey pgtype.Text) (EbookSetting, error)
	GetEpisodeForUser(ctx context.Context, arg GetEpisodeForUserParams) (PodcastEpisode, error)
	GetFileVersion(ctx context.Context, arg GetFileVersionParams) (FileVersion, error)
	GetLiveNodeByPath(ctx context.Context, arg GetLiveNodeByPathParams) (Node, error)
	GetMusicSettings(ctx context.Context, userID pgtype.UUID) (MusicSetting, error)
	GetMusicSettingsByApiKey(ctx context.Context, apiKey pgtype.Text) (MusicSetting, error)
	GetNode(ctx context.Context, id pgtype.UUID) (Node, error)
	GetNodeForUser(ctx context.Context, arg GetNodeForUserParams) (Node, error)
	GetPairingByCodeHash(ctx context.Context, deviceCodeHash string) (DevicePairing, error)
	GetPairingByUserCode(ctx context.Context, userCode string) (DevicePairing, error)
	GetPlayQueue(ctx context.Context, userID pgtype.UUID) (PlayQueue, error)
	GetPlayQueueEntries(ctx context.Context, userID pgtype.UUID) ([]GetPlayQueueEntriesRow, error)
	GetPlaylist(ctx context.Context, id pgtype.UUID) (Playlist, error)
	// Returns songs in a playlist ordered by position, joined with song details.
	GetPlaylistSongs(ctx context.Context, playlistID pgtype.UUID) ([]Song, error)
	GetPodcastChannelByFeed(ctx context.Context, arg GetPodcastChannelByFeedParams) (PodcastChannel, error)
	GetPodcastChannelForUser(ctx context.Context, arg GetPodcastChannelForUserParams) (PodcastChannel, error)
	// Returns the stored reading position for (user_id, document).
	GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetShare(ctx context.Context, id pgtype.UUID) (ResourceShare, error)
	GetSongByNode(ctx context.Context, nodeID pgtype.UUID) (Song, error)
	GetSyncSettings(ctx context.Context, userID pgtype.UUID) (SyncSetting, error)
	GetTrashedNodeForUser(ctx context.Context, arg GetTrashedNodeForUserParams) (Node, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserLanguage(ctx context.Context, id pgtype.UUID) (string, error)
	GetUserTOTP(ctx context.Context, userID pgtype.UUID) (UserTotp, error)
	HardDeleteNode(ctx context.Context, id pgtype.UUID) error
	HardDeleteSubtree(ctx context.Context, arg HardDeleteSubtreeParams) error
	// Audit log (A.7).
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Backup codes (A.3). One-time, argon2id-hashed.
	InsertBackupCode(ctx context.Context, arg InsertBackupCodeParams) error
	InsertBookAuthor(ctx context.Context, arg InsertBookAuthorParams) error
	InsertBookTag(ctx context.Context, arg InsertBookTagParams) error
	InsertFileVersion(ctx context.Context, arg InsertFileVersionParams) (FileVersion, error)
	InsertPlayHistory(ctx context.Context, arg InsertPlayHistoryParams) error
	// WebAuthn credentials (A.4). The full go-webauthn Credential is stored as JSON.
	InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (WebauthnCredential, error)
	ListAddressbookObjects(ctx context.Context, addressbookID pgtype.UUID) ([]AddressbookObject, error)
	ListAddressbooks(ctx context.Context, userID pgtype.UUID) ([]Addressbook, error)
	ListAllPodcastChannels(ctx context.Context) ([]PodcastChannel, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListBookmarks(ctx context.Context, userID pgtype.UUID) ([]Bookmark, error)
	ListCalendarObjects(ctx context.Context, calendarID pgtype.UUID) ([]CalendarObject, error)
	ListCalendars(ctx context.Context, userID pgtype.UUID) ([]Calendar, error)
	// Delta sync: changes after seq, with the node's current state.
	// LIMIT — pagination: large deltas aren't returned in a single chunk (3.1).
	// content_hash — lets the client tell a real change from a touch.
	ListChangesSince(ctx context.Context, arg ListChangesSinceParams) ([]ListChangesSinceRow, error)
	ListChangesSinceUnderPrefix(ctx context.Context, arg ListChangesSinceUnderPrefixParams) ([]ListChangesSinceUnderPrefixRow, error)
	ListChildren(ctx context.Context, arg ListChildrenParams) ([]Node, error)
	ListCompletedEpisodesByChannelDesc(ctx context.Context, channelID pgtype.UUID) ([]ListCompletedEpisodesByChannelDescRow, error)
	ListDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]Device, error)
	ListEpisodesByChannel(ctx context.Context, channelID pgtype.UUID) ([]PodcastEpisode, error)
	ListExpiredTombstones(ctx context.Context, deletedAt pgtype.Timestamptz) ([]ListExpiredTombstonesRow, error)
	ListFileNodesUnderFolder(ctx context.Context, id pgtype.UUID) ([]Node, error)
	ListFileVersions(ctx context.Context, nodeID pgtype.UUID) ([]FileVersion, error)
	ListInternetRadioStations(ctx context.Context, userID pgtype.UUID) ([]InternetRadioStation, error)
	ListLiveNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error)
	ListNewestEpisodesForUser(ctx context.Context, arg ListNewestEpisodesForUserParams) ([]PodcastEpisode, error)
	// Children of a node without owner scoping (for listing a shared folder after canAccess).
	ListNodeChildren(ctx context.Context, parentID pgtype.UUID) ([]Node, error)
	// Nodes that have more than keep versions (trimming candidates).
	ListNodesWithExcessVersions(ctx context.Context, keep interface{}) ([]pgtype.UUID, error)
	ListNotificationPrefs(ctx context.Context, userID pgtype.UUID) ([]ListNotificationPrefsRow, error)
	ListPlaylistsByUser(ctx context.Context, userID pgtype.UUID) ([]Playlist, error)
	ListPodcastChannelsForUser(ctx context.Context, userID pgtype.UUID) ([]PodcastChannel, error)
	ListPublicSettings(ctx context.Context) ([]Setting, error)
	ListQuotaCandidates(ctx context.Context) ([]ListQuotaCandidatesRow, error)
	ListRootNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error)
	ListSecretKeys(ctx context.Context) ([]string, error)
	ListSharesForResource(ctx context.Context, arg ListSharesForResourceParams) ([]ResourceShare, error)
	ListSharesForUser(ctx context.Context, sharedWithUser pgtype.UUID) ([]ResourceShare, error)
	// Returns accessible starred albums for a user, ordered by starred_at desc.
	// An album is accessible iff it contains at least one song owned by or shared with
	// the caller (same own ∪ shared_subtree filter as ListStarredSongs).
	// EXISTS (not JOIN songs) keeps stars→albums 1:1, so no DISTINCT is needed and
	// ORDER BY st.starred_at stays valid (DISTINCT + ORDER BY a non-selected column errors).
	ListStarredAlbums(ctx context.Context, userID pgtype.UUID) ([]ListStarredAlbumsRow, error)
	// Returns accessible starred artists for a user, ordered by starred_at desc.
	// An artist is accessible iff it has at least one accessible song (own ∪ shared).
	// EXISTS keeps stars→artists 1:1 (no DISTINCT), so ORDER BY st.starred_at is valid.
	ListStarredArtists(ctx context.Context, userID pgtype.UUID) ([]Artist, error)
	// Returns accessible starred songs for a user, ordered by starred_at desc.
	ListStarredSongs(ctx context.Context, userID pgtype.UUID) ([]Song, error)
	// Paths of trashed (soft-deleted) nodes — so a rescan doesn't re-import their files.
	ListTombstonedNodePaths(ctx context.Context, userID pgtype.UUID) ([]pgtype.Text, error)
	ListTrashNodes(ctx context.Context, userID pgtype.UUID) ([]Node, error)
	ListTrashedSubtree(ctx context.Context, arg ListTrashedSubtreeParams) ([]ListTrashedSubtreeRow, error)
	ListUnusedBackupCodes(ctx context.Context, userID pgtype.UUID) ([]BackupCode, error)
	ListUserIDs(ctx context.Context) ([]pgtype.UUID, error)
	// Users with used space (sum of live file sizes) — for the admin dashboard.
	ListUsersWithUsage(ctx context.Context) ([]ListUsersWithUsageRow, error)
	ListWebAuthnCredentials(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error)
	ListWebdavDevicesByEmail(ctx context.Context, email string) ([]Device, error)
	MarkBackupCodeUsed(ctx context.Context, id pgtype.UUID) error
	MarkQuotaNotified(ctx context.Context, id pgtype.UUID) error
	MaxPlaylistPosition(ctx context.Context, playlistID pgtype.UUID) (interface{}, error)
	NextChangeSeq(ctx context.Context, id pgtype.UUID) (int64, error)
	NotificationPrefsForEvent(ctx context.Context, arg NotificationPrefsForEventParams) ([]NotificationPrefsForEventRow, error)
	// Returns accessible songs in random order with optional genre/year filters.
	// Pass NULL for genre, from_year, to_year to skip those filters.
	RandomAccessibleSongs(ctx context.Context, arg RandomAccessibleSongsParams) ([]RandomAccessibleSongsRow, error)
	RatingsForUser(ctx context.Context, userID pgtype.UUID) ([]RatingsForUserRow, error)
	// Returns recent play_history rows for the caller, joined to song+album+artist.
	RecentPlayHistory(ctx context.Context, arg RecentPlayHistoryParams) ([]RecentPlayHistoryRow, error)
	RefreshAlbumSongCount(ctx context.Context, id pgtype.UUID) error
	RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) error
	// Rewrite disk_path of a node and its whole subtree on rename/move (mirrors the tree).
	RewriteSubtreePaths(ctx context.Context, arg RewriteSubtreePathsParams) error
	// Like RewriteSubtreePaths, but only for trashed nodes — so restoring doesn't
	// touch a LIVE node sharing the same disk_path (the name was reused after deletion).
	RewriteTombstonedSubtreePaths(ctx context.Context, arg RewriteTombstonedSubtreePathsParams) error
	// Returns accessible books matching a case-insensitive substring in title, author, or series.
	SearchAccessibleBooks(ctx context.Context, arg SearchAccessibleBooksParams) ([]Book, error)
	// Returns accessible albums whose name matches a case-insensitive substring.
	// Pass an empty string for q to match all albums.
	SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error)
	// Returns accessible artists whose name matches a case-insensitive substring.
	// Pass an empty string for q to match all artists.
	SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error)
	// Returns accessible songs whose title matches a case-insensitive substring.
	// Pass an empty string for q to match all songs.
	SearchSongs(ctx context.Context, arg SearchSongsParams) ([]SearchSongsRow, error)
	SetAddressbookName(ctx context.Context, arg SetAddressbookNameParams) error
	SetAlbumCover(ctx context.Context, arg SetAlbumCoverParams) error
	SetArtistCover(ctx context.Context, arg SetArtistCoverParams) error
	SetBookCoverPath(ctx context.Context, arg SetBookCoverPathParams) error
	SetBookMetadataEdited(ctx context.Context, arg SetBookMetadataEditedParams) error
	SetCalendarColor(ctx context.Context, arg SetCalendarColorParams) error
	SetCalendarName(ctx context.Context, arg SetCalendarNameParams) error
	SetDeviceTokenHash(ctx context.Context, arg SetDeviceTokenHashParams) error
	SetEbookCredentials(ctx context.Context, arg SetEbookCredentialsParams) error
	SetEpisodeDownloaded(ctx context.Context, arg SetEpisodeDownloadedParams) error
	SetEpisodeStatus(ctx context.Context, arg SetEpisodeStatusParams) error
	SetMusicCredentials(ctx context.Context, arg SetMusicCredentialsParams) error
	SetPodcastChannelCoverPath(ctx context.Context, arg SetPodcastChannelCoverPathParams) error
	SetPodcastChannelMeta(ctx context.Context, arg SetPodcastChannelMetaParams) error
	SetRating(ctx context.Context, arg SetRatingParams) error
	SetSharePasswordHash(ctx context.Context, arg SetSharePasswordHashParams) error
	SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error
	SharedAccessForUser(ctx context.Context, arg SharedAccessForUserParams) (SharedAccessForUserRow, error)
	// Returns accessible songs of a given genre excluding a specific artist, in random order.
	SimilarSongsByGenre(ctx context.Context, arg SimilarSongsByGenreParams) ([]SimilarSongsByGenreRow, error)
	SoftDeleteNode(ctx context.Context, id pgtype.UUID) error
	// Soft-delete a node and its whole subtree (disk is cleaned up by GC, step 0.6).
	SoftDeleteSubtree(ctx context.Context, arg SoftDeleteSubtreeParams) error
	// Returns accessible songs for a specific genre with pagination.
	SongsByGenre(ctx context.Context, arg SongsByGenreParams) ([]SongsByGenreRow, error)
	Star(ctx context.Context, arg StarParams) error
	StarredItems(ctx context.Context, userID pgtype.UUID) ([]StarredItemsRow, error)
	// Returns accessible songs for a given artist name ordered by caller's play count descending.
	TopSongsByArtistName(ctx context.Context, arg TopSongsByArtistNameParams) ([]TopSongsByArtistNameRow, error)
	TouchDevice(ctx context.Context, id pgtype.UUID) error
	// Delete versions beyond the keep newest; return snapshot paths for disk cleanup.
	TrimNodeVersions(ctx context.Context, arg TrimNodeVersionsParams) ([]pgtype.Text, error)
	UndeleteSubtree(ctx context.Context, arg UndeleteSubtreeParams) error
	Unstar(ctx context.Context, arg UnstarParams) error
	UpdateBookMetadata(ctx context.Context, arg UpdateBookMetadataParams) error
	UpdateInternetRadioStation(ctx context.Context, arg UpdateInternetRadioStationParams) (int64, error)
	UpdateNodeContent(ctx context.Context, arg UpdateNodeContentParams) (Node, error)
	UpdateNodeName(ctx context.Context, arg UpdateNodeNameParams) (Node, error)
	UpdateNodeParent(ctx context.Context, arg UpdateNodeParentParams) (Node, error)
	// Password change: new hash + bump token_version (invalidates all active sessions)
	// + clear the forced-change flag (A.2).
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdatePlaylistMeta(ctx context.Context, arg UpdatePlaylistMetaParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// A.5: persist the credential after a login (sign_count bumps; clone detection) + last used.
	UpdateWebAuthnCredential(ctx context.Context, arg UpdateWebAuthnCredentialParams) error
	// == addressbook_objects ==
	UpsertAddressbookObject(ctx context.Context, arg UpsertAddressbookObjectParams) (AddressbookObject, error)
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error)
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error)
	UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error)
	// == calendar_objects ==
	UpsertCalendarObject(ctx context.Context, arg UpsertCalendarObjectParams) (CalendarObject, error)
	UpsertEbookSettings(ctx context.Context, arg UpsertEbookSettingsParams) (EbookSetting, error)
	UpsertKnownLogin(ctx context.Context, arg UpsertKnownLoginParams) (bool, error)
	UpsertMusicSettings(ctx context.Context, arg UpsertMusicSettingsParams) (MusicSetting, error)
	UpsertNotificationPref(ctx context.Context, arg UpsertNotificationPrefParams) error
	UpsertPlayQueue(ctx context.Context, arg UpsertPlayQueueParams) error
	UpsertPodcastEpisode(ctx context.Context, arg UpsertPodcastEpisodeParams) error
	// Inserts or updates the reading position for (user_id, document). All mutable
	// fields are refreshed on conflict so the latest device wins.
	UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertSong(ctx context.Context, arg UpsertSongParams) (Song, error)
	UpsertSyncSettings(ctx context.Context, arg UpsertSyncSettingsParams) (SyncSetting, error)
	// TOTP 2FA (A.3). Secret is AES-GCM ciphertext.
	// Begin (or restart) TOTP setup: store an encrypted secret, not yet confirmed.
	UpsertUserTOTP(ctx context.Context, arg UpsertUserTOTPParams) error
}

var _ Querier = (*Queries)(nil)
