// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSavedItem = `-- name: ClaimSavedItem :execrows
UPDATE saved_items SET status = 'processing', error_msg = '', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ClaimSavedItem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimSavedItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFinishedDownloads = `-- name: DeleteFinishedDownloads :execrows
DELETE FROM saved_items WHERE kind = 'download'
  AND ((status = 'done' AND updated_at < $1) OR (status = 'error' AND updated_at < $2))
`

type DeleteFinishedDownloadsParams struct {
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedAt_2 pgtype.Timestamptz `json:"updated_at_2"`
}

func (q *Queries) DeleteFinishedDownloads(ctx context.Context, arg DeleteFinishedDownloadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedDownloads, arg.UpdatedAt, arg.UpdatedAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSavedItemForUser = `-- name: DeleteSavedItemForUser :one
DELETE FROM saved_items WHERE id = $1 AND user_id = $2
RETURNING kind, content_path, meta
`

type DeleteSavedItemForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type DeleteSavedItemForUserRow struct {
	Kind        string      `json:"kind"`
	ContentPath pgtype.Text `json:"content_path"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) DeleteSavedItemForUser(ctx context.Context, arg DeleteSavedItemForUserParams) (DeleteSavedItemForUserRow, error) {
	row := q.db.QueryRow(ctx, deleteSavedItemForUser, arg.ID, arg.UserID)
	var i DeleteSavedItemForUserRow
	err := row.Scan(&i.Kind, &i.ContentPath, &i.Meta)
	return i, err
}

const getSavedItemForUser = `-- name: GetSavedItemForUser :one
SELECT id, user_id, url, kind, title, status, error_msg, content_path, size_bytes, bytes_done, meta, created_at, updated_at, content_html, cookie_header FROM saved_items WHERE id = $1 AND user_id = $2
`

type GetSavedItemForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSavedItemForUser(ctx context.Context, arg GetSavedItemForUserParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, getSavedItemForUser, arg.ID, arg.UserID)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.ErrorMsg,
		&i.ContentPath,
		&i.SizeBytes,
		&i.BytesDone,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.CookieHeader,
	)
	return i, err
}

const listPendingSavedItems = `-- name: ListPendingSavedItems :many
SELECT id, user_id, url, kind, title, status, error_msg, content_path, size_bytes, bytes_done, meta, created_at, updated_at, content_html, cookie_header FROM saved_items WHERE status = 'pending' ORDER BY created_at LIMIT $1
`

func (q *Queries) ListPendingSavedItems(ctx context.Context, limit int32) ([]SavedItem, error) {
	rows, err := q.db.Query(ctx, listPendingSavedItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedItem{}
	for rows.Next() {
		var i SavedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Kind,
			&i.Title,
			&i.Status,
			&i.ErrorMsg,
			&i.ContentPath,
			&i.SizeBytes,
			&i.BytesDone,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHtml,
			&i.CookieHeader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedItems = `-- name: ListSavedItems :many
SELECT id, user_id, url, kind, title, status, error_msg, content_path, size_bytes, bytes_done, meta, created_at, updated_at, content_html, cookie_header FROM saved_items
WHERE user_id = $1
  AND kind <> 'download'
  AND ($4::text = '' OR kind = $4::text)
  AND ($5::text = '' OR status = $5::text)
  AND ($6::text = '' OR title ILIKE '%' || $6::text || '%' OR url ILIKE '%' || $6::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSavedItemsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Kind   string      `json:"kind"`
	Status string      `json:"status"`
	Q      string      `json:"q"`
}

// Downloads are an internal queue and never appear in listings.
func (q *Queries) ListSavedItems(ctx context.Context, arg ListSavedItemsParams) ([]SavedItem, error) {
	rows, err := q.db.Query(ctx, listSavedItems,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Kind,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedItem{}
	for rows.Next() {
		var i SavedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Kind,
			&i.Title,
			&i.Status,
			&i.ErrorMsg,
			&i.ContentPath,
			&i.SizeBytes,
			&i.BytesDone,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHtml,
			&i.CookieHeader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStaleSavedItems = `-- name: ResetStaleSavedItems :execrows
UPDATE saved_items SET status = 'pending', bytes_done = 0, updated_at = now()
WHERE status = 'processing'
`

func (q *Queries) ResetStaleSavedItems(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetStaleSavedItems)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retrySavedItem = `-- name: RetrySavedItem :execrows
UPDATE saved_items SET status = 'pending', error_msg = '', bytes_done = 0, updated_at = now()
WHERE id = $1 AND user_id = $2 AND status IN ('error', 'done')
`

type RetrySavedItemParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RetrySavedItem(ctx context.Context, arg RetrySavedItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, retrySavedItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSavedItemDone = `-- name: SetSavedItemDone :execrows
UPDATE saved_items
SET status = 'done', content_path = $2, size_bytes = $3, bytes_done = COALESCE($3, bytes_done),
    title = COALESCE(NULLIF($5::text, ''), title), meta = $4,
    content_html = NULL, cookie_header = NULL, updated_at = now()
WHERE id = $1 AND status = 'processing'
`

type SetSavedItemDoneParams struct {
	ID          pgtype.UUID `json:"id"`
	ContentPath pgtype.Text `json:"content_path"`
	SizeBytes   pgtype.Int8 `json:"size_bytes"`
	Meta        []byte      `json:"meta"`
	Title       string      `json:"title"`
}

// content_html/cookie_header are dropped once processed — transport, not storage.
func (q *Queries) SetSavedItemDone(ctx context.Context, arg SetSavedItemDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSavedItemDone,
		arg.ID,
		arg.ContentPath,
		arg.SizeBytes,
		arg.Meta,
		arg.Title,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSavedItemError = `-- name: SetSavedItemError :exec
UPDATE saved_items SET status = 'error', error_msg = $2, updated_at = now()
WHERE id = $1
`

type SetSavedItemErrorParams struct {
	ID       pgtype.UUID `json:"id"`
	ErrorMsg string      `json:"error_msg"`
}

func (q *Queries) SetSavedItemError(ctx context.Context, arg SetSavedItemErrorParams) error {
	_, err := q.db.Exec(ctx, setSavedItemError, arg.ID, arg.ErrorMsg)
	return err
}

const updateSavedItemProgress = `-- name: UpdateSavedItemProgress :execrows
UPDATE saved_items
SET bytes_done = $2, size_bytes = COALESCE($3, size_bytes), updated_at = now()
WHERE id = $1 AND status = 'processing'
`

type UpdateSavedItemProgressParams struct {
	ID        pgtype.UUID `json:"id"`
	BytesDone int64       `json:"bytes_done"`
	SizeBytes pgtype.Int8 `json:"size_bytes"`
}

func (q *Queries) UpdateSavedItemProgress(ctx context.Context, arg UpdateSavedItemProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSavedItemProgress, arg.ID, arg.BytesDone, arg.SizeBytes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSavedItem = `-- name: UpsertSavedItem :one

INSERT INTO saved_items (user_id, url, kind, title, content_html, cookie_header)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, url, kind) DO UPDATE SET
    content_html = COALESCE(EXCLUDED.content_html, saved_items.content_html),
    cookie_header = COALESCE(EXCLUDED.cookie_header, saved_items.cookie_header),
    updated_at = now()
RETURNING id, user_id, url, kind, title, status, error_msg, content_path, size_bytes, bytes_done, meta, created_at, updated_at, content_html, cookie_header
`

type UpsertSavedItemParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Url          string      `json:"url"`
	Kind         string      `json:"kind"`
	Title        string      `json:"title"`
	ContentHtml  pgtype.Text `json:"content_html"`
	CookieHeader pgtype.Text `json:"cookie_header"`
}

// Saved items: read-later articles and server-side downloads (internal queue).
// Re-save refreshes the client-supplied HTML/cookies (a newer browser state)
// but never resets the status.
func (q *Queries) UpsertSavedItem(ctx context.Context, arg UpsertSavedItemParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, upsertSavedItem,
		arg.UserID,
		arg.Url,
		arg.Kind,
		arg.Title,
		arg.ContentHtml,
		arg.CookieHeader,
	)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.ErrorMsg,
		&i.ContentPath,
		&i.SizeBytes,
		&i.BytesDone,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.CookieHeader,
	)
	return i, err
}
