// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncSettings = `-- name: GetSyncSettings :one
SELECT user_id, enabled, folder_node_id, epoch, created_at, updated_at FROM sync_settings WHERE user_id = $1
`

func (q *Queries) GetSyncSettings(ctx context.Context, userID pgtype.UUID) (SyncSetting, error) {
	row := q.db.QueryRow(ctx, getSyncSettings, userID)
	var i SyncSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.FolderNodeID,
		&i.Epoch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSyncSettings = `-- name: UpsertSyncSettings :one
INSERT INTO sync_settings (user_id, enabled, folder_node_id, epoch, updated_at)
VALUES ($1, $2, $3, 1, now())
ON CONFLICT (user_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    folder_node_id = EXCLUDED.folder_node_id,
    epoch = CASE
        WHEN sync_settings.enabled IS DISTINCT FROM EXCLUDED.enabled
          OR sync_settings.folder_node_id IS DISTINCT FROM EXCLUDED.folder_node_id
        THEN sync_settings.epoch + 1
        ELSE sync_settings.epoch
    END,
    updated_at = now()
RETURNING user_id, enabled, folder_node_id, epoch, created_at, updated_at
`

type UpsertSyncSettingsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Enabled      bool        `json:"enabled"`
	FolderNodeID pgtype.UUID `json:"folder_node_id"`
}

func (q *Queries) UpsertSyncSettings(ctx context.Context, arg UpsertSyncSettingsParams) (SyncSetting, error) {
	row := q.db.QueryRow(ctx, upsertSyncSettings, arg.UserID, arg.Enabled, arg.FolderNodeID)
	var i SyncSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.FolderNodeID,
		&i.Epoch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
